=pod

=head1 Dancer app


=head2 TODO

=over 4

=item add syntax highlight for pod2html

=item add documentation to code

=item add recursive dir support

=item add session support

=item add blog and use mongoDB as its backend

=back



=head2 DONE

=over 4

=item display subdir and files

render files based on extension (currently support markdown, org and pod)

=item add the module dir and render pod

=back

=cut



