遥远的曾经2012
#+SETUPFILE: C:/Users/echo/Dropbox/org/org-templates/t0.org
#+LINK_HOME:index.html
#+LINK_UP:index.html

** [2012-02-28 Tue 19:14] 故事 

如果你有很多时间耳朵和大脑是闲着的，可以在[[http://www.justing.com.cn/][这里]]找这些故事来听。
以下链接是文字版。我自己是听的，所以并没有看。

*** [[http://www.21ccom.net/articles/zgyj/gqmq/2011/1129/49518.html][差距]]
*** [[http://www.douban.com/group/topic/22566413/][如果我在即将坠机的航班上睡着了]]
*** [[http://bbs.9430.cn/dispbbs.asp?boardid=26&Id=5788][像鸟一样的飞翔]]
*** [[http://www.tianyabook.com/renwu2005/js/a/andun/hj/001.htm][快乐是我的面具]]
*** [[http://www.tianyabook.com/renwu2005/js/a/andun/hj/002.htm][快乐不是一辈子的面具
]]
** [2012-02-29 Wed 23:02] 寓言

众 税 吏 和 罪 人 都 挨 近 耶 稣 ， 要 听 他 讲 道 。

2  法 利 赛 人 和 文 士 私 下 议 论 说 ： 这 个 人 接 待 罪 人 ， 又 同 他 们 吃 饭 。

3  耶 稣 就 用 比 喻 说 ：

4  你 们 中 间 谁 有 一 百 只 羊 失 去 一 只 ， 不 把 这 九 十 九 只 撇 在 旷 野 、 去 找 那 失 去 的 羊 ， 直 到 找 着 呢 ？

5  找 着 了 ， 就 欢 欢 喜 喜 的 扛 在 肩 上 ， 回 到 家 里 ，

6  就 请 朋 友 邻 舍 来 ， 对 他 们 说 ： 我 失 去 的 羊 已 经 找 着 了 ， 你 们 和 我 一 同 欢 喜 罢 ！

7  我 告 诉 你 们 ， 一 个 罪 人 悔 改 ， 在 天 上 也 要 这 样 为 他 欢 喜 ， 较 比 为 九 十 九 个 不 用 悔 改 的 义 人 欢 喜 更 大 。

8  或 是 一 个 妇 人 有 十 块 钱 ， 若 失 落 一 块 ， 岂 不 点 上 灯 ， 打 扫 屋 子 ， 细 细 的 找 ， 直 到 找 着 麽 ？

9  找 着 了 ， 就 请 朋 友 邻 舍 来 ， 对 他 们 说 ： 我 失 落 的 那 块 钱 已 经 找 着 了 ， 你 们 和 我 一 同 欢 喜 罢 ！

10  我 告 诉 你 们 ， 一 个 罪 人 悔 改 ， 在 神 的 使 者 面 前 也 是 这 样 为 他 欢 喜 。 」

11  耶 稣 又 说 ： 一 个 人 有 两 个 儿 子 。

12  小 儿 子 对 父 亲 说 ： 父 亲 ， 请 你 把 我 应 得 的 家 业 分 给 我 。 他 父 亲 就 把 产 业 分 给 他 们 。

13  过 了 不 多 几 日 ， 小 儿 子 就 把 他 一 切 所 有 的 都 收 拾 起 来 ， 往 远 方 去 了 。 在 那 里 任 意 放 荡 ， 浪 费 赀 财 。

14  既 耗 尽 了 一 切 所 有 的 ， 又 遇 着 那 地 方 大 遭 饥 荒 ， 就 穷 苦 起 来 。

15  於 是 去 投 靠 那 地 方 的 一 个 人 ； 那 人 打 发 他 到 田 里 去 放 猪 。

16  他 恨 不 得 拿 猪 所 吃 的 豆 荚 充 饥 ， 也 没 有 人 给 他 。

17  他 醒 悟 过 来 ， 就 说 ： 我 父 亲 有 多 少 的 雇 工 ， 口 粮 有 馀 ， 我 倒 在 这 里 饿 死 麽 ？

18  我 要 起 来 ， 到 我 父 亲 那 里 去 ， 向 他 说 ： 父 亲 ！ 我 得 罪 了 天 ， 又 得 罪 了 你 ；

19  从 今 以 後 ， 我 不 配 称 为 你 的 儿 子 ， 把 我 当 作 一 个 雇 工 罢 ！

20  於 是 起 来 ， 往 他 父 亲 那 里 去 。 相 离 还 远 ， 他 父 亲 看 见 ， 就 动 了 慈 心 ， 跑 去 抱 着 他 的 颈 项 ， 连 连 与 他 亲 嘴 。

21  儿 子 说 ： 父 亲 ！ 我 得 罪 了 天 ， 又 得 罪 了 你 ； 从 今 以 後 ， 我 不 配 称 为 你 的 儿 子 。

22  父 亲 却 吩 咐 仆 人 说 ： 把 那 上 好 的 袍 子 快 拿 出 来 给 他 穿 ； 把 戒 指 戴 在 他 指 头 上 ； 把 鞋 穿 在 他 脚 上 ；

23  把 那 肥 牛 犊 牵 来 宰 了 ， 我 们 可 以 吃 喝 快 乐 ；

24  因 为 我 这 个 儿 子 是 死 而 复 活 ， 失 而 又 得 的 。 他 们 就 快 乐 起 来 。

25  那 时 ， 大 儿 子 正 在 田 里 。 他 回 来 ， 离 家 不 远 ， 听 见 作 乐 跳 舞 的 声 音 ，

26  便 叫 过 一 个 仆 人 来 ， 问 是 甚 麽 事 。

27  仆 人 说 ： 你 兄 弟 来 了 ； 你 父 亲 因 为 得 他 无 灾 无 病 的 回 来 ， 把 肥 牛 犊 宰 了 。

28  大 儿 子 却 生 气 ， 不 肯 进 去 ； 他 父 亲 就 出 来 劝 他 。

29  他 对 父 亲 说 ： 我 服 事 你 这 多 年 ， 从 来 没 有 违 背 过 你 的 命 ， 你 并 没 有 给 我 一 只 山 羊 羔 ， 叫 我 和 朋 友 一 同 快 乐 。

30  但 你 这 个 儿 子 和 娼 妓 吞 尽 了 你 的 产 业 ， 他 一 来 了 ， 你 倒 为 他 宰 了 肥 牛 犊 。

31  父 亲 对 他 说 ： 儿 阿 ！ 你 常 和 我 同 在 ， 我 一 切 所 有 的 都 是 你 的 ；

32  只 是 你 这 个 兄 弟 是 死 而 复 活 、 失 而 又 得 的 ， 所 以 我 们 理 当 欢 喜 快 乐 。
** [2012-03-01 Thu 19:09] 距离

我刚才看了同学分享的文章《其实，我们并不在同一起跑线》;几天前，偶然听到余华写的《差距》。 写的都是不同人的生活。我也写下我的经历。

（一）

我昨天，在教堂，吃饭的时候，有两个人和我们同桌，大家聊起一种美国人吃的甜点，他们问，在中国 这个流行么？然后又问我们，中国人吃什么甜点呢？我们几个相互观望，没有统一的答案。

我只好，对我身边的一个人说，中国太大了，不同地方的人的饮食不一样。城市和农村的饮食也不一样，相对不如美国那么统一。 (在我的家乡，甜点这个东西，只有过节，或者婚丧嫁娶的时候才会吃。几十年前，吃一口白面馒头都是一个梦想。) 

如果再延伸一些，人与人的衣食住行，都不一样。


（二）

我老师的女儿，应该是移民二代，工作是律师，小提琴拉的好。老师很引以为傲。当然，这与自身的努力，分不开，另一方面， 她一开始就有了很大的优势。当律师，要上法学院，奖学金很少。即使是一般的美国家庭，供应起来也不轻松。至于小提琴，如果是在中国，很多的家庭的年收入也不够购买一个。（我初中的时候，在我外祖父那看到了我们县的地方志，我看那些年收入的统计数字， 我惊奇于那数字怎么那么小，我外祖父说，这个还是有夸大的成分。）

我老师不只一次的说，你看人家美国小孩，都有个特长（这个也是以偏概全，美国小孩，并非都有特长，有唬人的成分）。让人有何不食糜肉之感。很多人努力发展特长，也有很多人拼命挣生存。

（三）

即使是校内也不同，形形色色的人，更新不同的状态，照片。很多人的目前的生活，对于另外的一些人来说，已经是天堂了。或者，不管怎么努力都是注定无法到达的。

（四）

教堂组织一些促进国际生和美国学生交流的活动。有时候，我跟他们一起去一个政府建立的社区，供穷人居住。我们的活动就是跟那里的小孩子玩。学生之中，除了我，都是白人，而小孩子，都是黑人。看着他们天真的玩耍，我都觉得不可思议, 梦幻一般。马丁路德的我有一个梦想， 其实是我有一个预言（虽然还有很多问题依旧存在）。

“我今天有一个梦想。我梦想有一天，亚拉巴马州能够有所转变，尽管该州州长现在仍然满口异议，反对联邦法令，但 有朝一日，那里的黑人男孩和女孩将能与白人男孩和女孩情同骨肉，携手并进。” ----马丁路德金《我有一个梦想》

我们所在的州是阿拉巴马，从学校到那个社区，要经过一条路叫马丁路德金路。当我看到路牌的时候，跟他们说，我高中的时候学过《我有一个梦想》。


（五）

网上流传着不尽的高富帅与矮矬穷的故事。有玩笑的成分在里面，但无法不承认，其中赤裸裸的事实。

如果高富帅的儿子将来还是高富帅，矮矬穷没有翻身的机会。甚至连一点梦想都粉碎了之后，会怎么样呢？

有多少人挤破头出来，在使馆门口忐忑不安的排长队，是因为看不到希望在哪里？

我刚才看了同学分享的文章《其实，我们并不在同一起跑线》;几天前，偶然听到余华写的《差距》。 写的都是不同人的生活。我也记录我的经历。

（一）

昨天，在教堂，吃饭的时候，有两个美国人和我们同桌，大家聊起一种美国人吃的甜点。他们问，在中国这个流行么？然后又问我们，中国人吃什么甜点呢？我们几个相互观望，没有统一的答案。

我只好，对我身边的一个人说，中国太大了，不同地方的人的饮食不一样。城市和农村的饮食也不一样，相对不如美国那么统一。 ( 在我的家乡，甜点这个东西，只有过节，或者婚丧嫁娶的时候才会吃。三十年前，吃一口白面馒头都是一个梦想。) 

如果再延伸一些，人与人的衣食住行，都不一样。


（二）

我老师的女儿，应该是移民二代，工作是律师，小提琴拉的好。老师很引以为傲。当然，这与自身的努力，分不开，另一方面， 她一开始就有了很大的优势。当律师，要上法学院，奖学金很少。即使是一般的美国家庭，供应起来也不轻松。至于小提琴，如果是在中国，很多的家庭的年收入也不够购买一个。（我初中的时候，在我外祖父那看到了我们县的地方志，我看那些年收入的统计数字， 我惊奇于那数字怎么那么小，我外祖父说，这个还是有夸大的成分。）

我老师不只一次的说，你看人家美国小孩，都有个特长（这个也是以偏概全，美国小孩，并非都有特长，有唬人的成分）。让人有何不食糜肉之感。很多人努力发展特长，也有很多人拼命挣生存。

（三）

即使是校内也不同，形形色色的人，更新不同的状态，照片。很多人的目前的生活，对于另外的一些人来说，已经是天堂了。或者，不管怎么努力都是注定无法到达的，像天堂一样无法接近。近乎残酷的现实是，我们都生活在一个地球上。

（四）


网上流传着不尽的高富帅与矮矬穷的故事。有玩笑的成分在里面，但无法不承认，其中赤裸裸的事实。

如果高富帅的儿子将来还是高富帅，矮矬穷没有翻身的机会。甚至连一点梦想都粉碎了之后，会怎么样呢？

有多少人挤破头出来，在使馆门口忐忑不安的排长队，是因为看不到希望在哪里？
** [2012-03-23 Fri 22:12] The End of Entomology

大部分人听说过虫子。昆虫，熟悉的人就少了。在美国也是这样，你说“bugs”人人都知道，insect 知道的人就少些。Entomology 很多人都不知道。

大学后两年，各种课程都是围绕昆虫学来转。我逃课多，去了也不怎么听课。考试背背，现在几乎忘光了。

植物保护专业到了硕士阶段就细分为植物病理与昆虫学。我现在尚不知道我为什么当初选了昆虫，而不是病理。研究生的第一门课即是昆虫分类。记不完的虫子的名字。虽然只要求科名，
但是要求拉丁文。大约花了10天时间，从早到晚，每天坐在教室整理昆虫标本。考完试，交完标本。立即就把没整理完得虫子给扔掉了。
想想，还是有收获的，在路上见到一个虫子，就会停下了，看看，大约哪个科，立即就有印象了。看完就后悔了，真挺无聊的。

然后，这学期有一门必修的昆虫形态学的课。老师很老了，之所以还教，大约是除了他，系里没有人可以教这门课了。老先生讲课信马由缰。10多个人上课，鲜有对这门课感兴趣的。
大约二三个人听讲。老师对于我们这种状态当然清楚，无可奈何。作为学生，也很无奈。一次，老先生感慨昆虫形态学的没落：“Snograss 死了， John 死了”然后就不说了。
（这个课主要学习昆虫的结构，名称，演化等等，Snograss 是这个领域的老大）。老先生为了鼓励学生听课，说，想想这个问题吧，你可能是世界上唯一一个思考这个问题的人。
至少，我是不为所动。

我大学专业是植物保护，植物学也算是一门专业基础课。大学学了一整年的植物学。
学校的植物应该有几百种。我来自北方，气候与重庆不同。直到离开，认识的不足百种。仍然没法与本地同学相比。奥本这个地方
气候与重庆类似，但是植被迥然不同。只认识常见的几种。
** [2012-03-29 Thu 19:37]  女博士的忧愁

周四到了，很庆幸又活过了一周。

要说的是我看的一个帖子。

*** [[http://www.mitbbs.com/article_t/Biology/31649665.html][女生读完生物phd何去何从--忧愁的无法入睡 请各位前辈指点一下]]

原帖太长，以下是大意：

发帖人是女生物phd，老板被学校炒了，作为学生只有提前毕业。但是她的研究领域是果蝇遗传学，工作不好找，博后也不好找，
回国貌似也不好办。说实话，女孩子可以嫁人。但是她已经有了比她小，正在读博的那朋友。

然后，下面一堆回复，其中一个印象比较深刻。
---------

你一个女的

1.一不该，你读了博士这个学位

2.二不该，你跳了生物这个大坑

3.三不该，你找了个小弟弟男友

一和二你都是改不了的了，也就三可以试试看能不能改。

一当然也可以改，找技工的位置的时候，不妨就把读博的经历改成学校里做技工。反正
你觉得混碗饭就行，所以博士做技工也无所谓。

大叔说句心里话，普通的女的，你真不要读博士，生物博士就更不要谈了。
-------------------
** [2012-04-02 Mon 13:35] go 语言的问题

*** 如何写swap函数？也即是如何能像C语言那样引用取值，复制取值
** [2012-04-05 Thu 21:16] 故事（二） 


*** [[http://mjlsh.usc.cuhk.edu.hk/Book.aspx?cid=4&tid=166][母亲和我]] 熊景明

这个写母亲，也写了百余年几代人的兴衰变迁。

*** [[http://www.douban.com/note/188265875/][母亲]] 刘汀

与作者同为北方人，经历很多地方惊人的相似。
** [2012-04-19 Thu 19:51] 我弟弟的2010

年命如朝露
人生忽如寄
寿无金石固
** [2012-05-06 Sun 22:31] 下雨了

日子无聊到，下点雨就足以让人兴奋的地步了。
** [2012-05-23 Wed 15:03] The End of Entomology (II)

白蚁, bedbug, 蟑螂

也许你无法想象，竟然有很多人研究这些虫子。不仅有，而且还有个专门的会议。
抱着打酱油的心态去了城市昆虫会议，发现，多数人比我还酱油。

搞学术的早已经被搞工业的甩在了后面，学术界靠过去积累的信誉生存，吃老本，为公司做广告。

坐山吃空,总不是好事。

好消息是，很多研究者都已经将近退休；
坏消息是这个行业，在学术界基本没有了生存空间。
** [2012-05-30 Wed 20:50] 追踪伤害儿子的杀手


我终于找到伤害我儿子的杀手。

三年的时间。

但是，我们找到了。

-----
需要澄清的是：我的儿子还活的很好。
然而，我和我的妻子对她的死有责任。
-----

我的儿子Bertran has a new genetic disorder.

Patient O.

为了追踪凶手，杜克大学的一个研究小组分析了我，我的妻子，和我的儿子的
whole-exome 

We discovered that my son inherited two different (thus-far-unique) mutations in the same gene--the NGLY1 gene--which encodes the enzyme N-glycanase 1. Consequently, he cannot make this enzyme.

My son is the only human being known to lack this enzyme.

Below, I'm documenting our journey to the unlikeliest of diagnoses.

This is a story about the kind of hope that only science can provide
** [2012-06-20 Wed 20:12] 找兼职的经历，找Perl兼职的请看
谢谢China Perl mailing，我从各位的帖子中学习了很多。更幸运的是一个星期前，借助此邮件列表，我找到了一份Perl的兼职。

招聘者给了一个fasta格式的文件，我学Perl就是因为将来想往生物信息学发展。所以，我看的那个fasta格式的文件后，就按照要求写出来Perl版，为了增加我的竞争力，我又写了R版。发过去后，没想到立即得到了回复。看招聘者说他也在美国，我觉得这个世界真小。

然后，招聘者打电话给我，我们谈了一下，大致的结果是，他愿意给我些项目，我跟着他学，免费编代码。的确如招聘者所说，我在美国读硕士，学校补助基本够用，所以我可以免费做，我当然有我的打算，如果我能学到些实际的东西，招聘者又是在该领域的研究者，将来我申请Phd还可以给我写推荐信，这些都不是钱可以买到的。

我们谈好的下一个星期一，他给我发来一个文件，要做些基本统计，用R和Perl交互，做boxplot。我熟悉R，我觉得对于统计，作图，还是R（R是当今最流行的统计语言，应该没有之一）顺手，所以很快写了R的版本，只用了25行代码（自认为Perl的代码不可能少于100行，画图还要调用R，当然可能还有其他的module可用。）。

我把R代码发过去后，又发了一封邮件，招聘者说周末他打电话给我，谈Phd的事情，以及可能做得项目。我们的谈话，让我觉得招聘者在给我画大饼，以使我免费给他干活。具体来说，如果我通过学校的申请，phd的第二年可以选他的实验室；我毕业了，万一没处去，可以到他实验室做个临时工，可以保身份。

和他的谈话使我觉得，如果我免费跟他干了一年，他到时翻脸不认人，我什么都没有得到。我跟他要数据的信息，他只跟我说，这是一个group，那是一个factor。我学不到东西。所以，我觉得不能免费干，给他发邮件，说我不愿意搞这个方向了，但是我可以为钱编代码。他回复说，我的要求很合理，他在国内招的也有人，2000—2500一个月，隔天一个项目，学不到什么东西的。我说，我可以写Perl也可以写R，400 美元吧。

然后他回复说，他懂Perl，希望我用Perl写。话锋一转，说，我还没有仔细看过你写的Perl,我再给你一个Perl项目，看看你的Perl如何吧。

然后，他给我分享了一个500M的folder，让我在我电脑上run。首先是有typo, 然后有个method找不到，但是有两个与之相似的，我发邮件故去问，告诉了我用哪个。然后又有一个文件找不到，结果第二天回复邮件说，Google drive的问题，没有同步完毕，同步
完毕通知你。下午发来邮件说，你把文件解压，运行下，有个bug，修复了咱们正式谈part time job的事情。我把文件解压一看4万多个文件（原来是google drive 的性能不行）。我觉得还是算了吧，没必要折腾了。本人水平确实有限，我给他编完R的程序，他就把主要的库给我了，深度大约10的hash
看的我头皮确实发麻。

开学的时候，新生培训的大妈，告诉我们，提防你们自己人，最可能骗你的是你自己人。还好，我及时提及了钱的事情。

这一个星期，我成长了很多，感谢那些免费教我认识人和事的人。我和招聘者的57封邮件以后可以留着给我的孩子做教材，
可惜两个电话没有录音。

作为一个弱者，我没有物质的东西可以回报，但我可以提醒某些人，Perl写成那个样子，就不要再写Perl了，改写python吧。
写Perl代码需要智商的。即使写Perl，也写写Perl 5 的代码。

以上是我，应聘兼职，因自身水平有限，而自我放弃的经历。

====================================

另外，有人问，既然是长期的项目，为什么不招个学生呢？

我来回答吧，在美国，学生太贵了相比中国而言；美国研究生，很多专业，不是因为你学东西，你做试验就是应该的，美国很多专业的研究生，
尤其生物类Phd，学费是不收的，另外，每个月还有相应的补助，我所在的学校一年15000 USD，在某人所在的学校，每年25000USD。
http://www.uthsc.edu/grad/IBS/stipends_scholarships.php 即使这样很多美国人，还是不读。因为本科就能找到不错的工作，维持中产。
但是，对于中国人，这个与在国内读，简直就是天堂了，那么多人挤破头皮来美国读书，最大的原因就是这个，尤其对于穷人。
这个钱要导师给的。根据某人的算计在国内招每月2000—2500，无需再问为什么不招个学生呢？

另外，学生也不是好招的，根据我所看到的招生信息，学生第一年的钱是学校付的，在这期间学生可以在实验室轮转，第二年才选
实验室，学生都不傻，不是说老师要我，我就去非得去他实验室的。至少，我要看看老师会不会让我免费干活吧。

======================================

另外，如果，有非找兼职的进来了，既然读到这个地方了，我总要告诉你点东西，让你不觉得我浪费你时间吧，
有一条，请记住，不要让你的孩子学生物相关的专业。收入不行，会对人的行为产生影响。或者说，你的收入决定你的行为，品格之类。
我见过一些人，我猜测如果他们在国内应该是很好的人，但是到了这边，生活的艰难，让人的品性随之变化。

======================================

这件事情到此为止了，如果打扰到您，很抱歉。
** [2012-07-15 Sun 15:19] bioending
标 题: 我们必须寻求改变
发信人: bioending (supersmart), 信区: Biology
标 题: 我们必须寻求改变
发信站: BBS 未名空间站 (Wed Nov 21 17:57:19 2007)

生物相关领域的学生和postdoc, 在在美国的中国人中占了很大比例，而这个人群
的收入则是处于最低的位置，除了往faculty这条辛苦一世的路上挤，或者甘于做万年
postdoc，找公司的路也比别的专业艰难许多。至于转行的那部分，到目前为止还属于
小部分。

为什么生物研究这条路越走越艰难，究其原因，还是市场的供需关系决定的，我们
属于供过于求的劳动力。金字塔结构的医学突破发现决定了美国为了发展基础医学研究
，需要大数量的受过专门training的劳动力，而大多美国本国的优秀人才都会选择回报
更大的工作，所以，从小重视科学教育的中国教育体系培养出来的中国学生们，便成为
美国研究机构的首选。很大一部分来美国读PhD的都是中国四大生物学院世家出身，当
年都是顶尖的学生。但这并不意味着由这群顶尖的人才支撑起来的生物研究真的需要这
么多顶尖的人才，看看美国的学生就知道，大多数进graduate school的这些都不是最
聪明的学生，虽然Harvard等少数几个学校里会有不少放弃读医学院，法学院而真的对
研究感兴趣而且也真正拔尖的学生，但第一，这是少数，第二，这几个学校PhD毕业转
去做咨询，投行，知识产权的也比别的学校比例要高得多。有诺贝尔得奖者说过，往往
最好的生物学家是大学里B average的学生，其实道理很简单，大多数留在这里的人都
不是top student。研究生物，对于抽象思维要求很低，对于数学只有少数计算，进化
和结构研究方面用得到，对于逻辑思考由于不需要很敏捷的反应一般人的逻辑思考能力
慢慢想绰绰有余。真正需要的是大量的时间投入，不知疲倦的反复尝试和好的运气。所
以，一将功成万骨枯，能有大发现的是少数，美国的科研经费的系统更是保证了对一个
问题的大于1x coverage，就是让你们都去试，有一个试出来就好。对于一个国家来说
，这种系统是符合国家利益的，生物医学的发展，也许这也是最好的模式，但是问题是
，美国现在的大规模基础研究来支持少量有价值的发现，牺牲的并不是它自己的民众，
而是让大量的外国人才来填这个巨大的坑。如果美国用同样的资本来使用本国的劳动力
来做这些研究，它能得到什么样的结果？只有两个可能性，其一，为了有高素质的研究
人员，必须提高报酬，在资本投入不变的情况下研究规模缩小。其二，为了维持规模，
现有人员配备结构发生改变，低学历技术支持人员比例上升，高学历研究人员比例下降
。这两种都不是美国希望看到的。

到这里，为什么这是供需关系决定的也就显而易见了，由于中美人均收入的差别，
同样的低收入在未出国的中国人眼里并不那么低，于是美国就可以用极低的成本使用大
量高素质的劳动力。而中国的态度则起了推波助澜的作用，中国一直希望科教兴国，所
以也鼓励留学生到美国来学习先进的科学技术。对生命科学的鼓吹更是在上个世纪末达
到了顶点。而美国则利用这样的心理把这些人都塞到了一个理论相对落后，需要大量人
力去牺牲的学科里，其结果就是中国其实吃了个大亏，这些做基础生物研究的能够带给
中国的，其实太少了。这么一堆高素质的人才，都蹉跎在了美国实验室里，等回到中国
，顶着长江的名号，能为中国做什么？这里面，美国招人的学校看重中国人好用聪明勤
奋听话，中国的学生看重美国学校名气好不用自己花钱读书还有奖学金受人羡慕，中国
找海龟的大学要给自己学校提升形象更好骗科研金费，回国的人看重可以常回中国受人
敬仰加腐败更好骗钱。当然，这个不是绝对适用，在这里做得很好希望在国内做得更好
并利用国内low labor cost和人才的也有，想回国为国家做些贡献的也有，但是结果并
没有什么区别，他们只是没有看到自己在这一个big picture中的位置。

大的方面说完了，再说说从个人利益方面。作为一个民主的时代，其实大家不必为
重视个人利益而羞愧，这个世界的运行规则就是大家都在不违反道德的框架下实现自己
的个人价值，这样得到的结果就是会对大多数人有利的结果。相信很多人都是抱着对科
学研究的憧憬和热情来到美国的，我们从小的教育也一直鼓励做科学家，虽然这并不是
个很合理。科学家这个职业，是在物质极大丰富，有些人开始有能力探索满足自己的求
知欲和好奇心才产生的职业，在中国这个远远没有达到富足的国家鼓励大家去做科学家
，也只能是文化大革命那个时期的思想造就的人处于社会主流时对教育的要求。但这也
就造成了一个时代的留学生或多或少愿意在不算好的物质条件下投身科学研究。许多人
会说自己对生物研究也是有兴趣的，其实很多时候是自欺欺人，在全身心投入的情况下
，其实一个人对自己做的事产生一些兴趣是很正常的，这并不代表他真的对这个职业有
兴趣。很大一部分人根本对别的职业了解很少，甚至片面的否定那些金融，经济相关的
职业，认为那些intellectually inferior，其实完全是盲目的自大，去读一读现代的
经济学，也许你会发现经济学比bioscience更像science，而投行对数学的要求，也比
大多数分子细胞生物学家们懂得要多，咨询要的逻辑思考，比很多cell paper的实验
design也要更smart。只要走出去看一看，就会发现很多工作都是非常challenging而又
能够发挥你的聪明才智的。但是由于这些工作对社会创造财富有直接的贡献，这些工作
带来的报酬要远远高于普通教授的工资，更不要说是Postdoc。有些人会说他们不care
收入比别人少，他们更enjoy做研究带来的乐趣跟成就感，但是到底给你成就感的是什
么？是你真的有了什么跨时代的发现？真的带来了什么对人类社会的改变？对大多数做
这一行的来说，成就感还是来自发了nature science cell的paper，拿到了大的grant
，到了哪个好的学校做教授，拿到了tenure。这些其实只是成功带来的成就感，在别的
行业也一样会得到。但是想一想你真的为这个社会创造了什么吗？一篇nature的paper
，全世界也许有几百个和你一样的科学家会读上一读，其中可能有几十个会仔细的读，
然后可能有10来个人会根据你的实验想点东西做，但是这样的成就就是你人生想要的成
就吗？这个职业真的比别人崇高吗？我并不是说没有人应该投身于科学研究，我的
point是，做研究并不是一件有多么崇高意义的事，并不能给人额外的成就感，那么它
的价值也应该在报酬上得到应有的体现。相对于别的博士，从事生物研究的在博士之后
还要经过漫长的博士后才有可能成为教授，而且是在淘汰率相当高的情况下。那么对于
这一行没有真正热爱的人来说，实在是不值，而对于这一行真的热爱而又有才能的人来
说，这一行的报酬没有达到可以让他们的价值得到体现的水平，所以，这样的情况对生
物研究的所有人都是不公平的。有些人甘于拿低工资卖苦力，这是中国传统宣扬的所谓
的美德，但是在现代社会的价值取向中，这并不被认为是美德。

看起来这是一个会长期存在的问题，但是从这几年的发展趋势看，我认为这个问题
在不久的将来就不会再存在。前面提到过，对生命科学的鼓吹在20世纪90年代中期达到
了顶峰，那时候的顶尖学校的生科院，考分绝对是全校最高的三名之内，更是大量高考
状元的去处。究其原因，一方面是对生命科学的盲目崇拜，一方面是出国容易的名声。
但是随着中国大众对世界的了解在90年代末互联网蓬勃发展的带动下日渐正常化后，对
生命科学的畸形追捧也就慢慢冷却。生科生源的相对素质逐年下滑是个不争的事实，到
了今时今日，生科的分数线再也不可能与国际金融等专业一争短长。同时，国内经济的
高速增长，特别是北大清华复旦所在城市的繁荣以及众多机会的出现使得出国不再是很
多最优秀人才的第一选择，即使想出国的人，也意识到出国绝不该为了到美国而出国，
很多更热门的专业同样有出国机会，而且能提供更好的发展机会。在这样的形势下，整
体出国读生物的中国学生素质也开始滑坡。那些已经在美国的留学生中学校好，能力强
的往往寻找其他的出路而离开了学术界，留下的少数是确实感兴趣，也有实力想要冲击
faculty之路的，更多的是需要一个过渡去找一份公司或者别的工作的。新来的这些留
学生，作为80后的一代，更是比以前的要更自我和现实的多，加之在国内有更好的物质
条件，这一代早早做好打算并付诸行动离开研究这一行当的比以前也多得多。照这个趋
势发展，中国的优秀的人才将减少投入美国的生物研究，faculty这条路的竞争也会稍
稍缓和一些。

但这也正是目前在读PhD和postdoc们的悲哀，在不久的将来，他们现在面对的问题
将成为历史遗留问题，就像文革中失去教育机会的一代。他们之后的新的一代在拥有更
多机会的环境中在社会中将成为更高等的人群，而他们曾经的优秀，曾经的风光将没有
人会记得和理解。如果现在不寻求改变，这个人群就将沿着这条轨迹归于消沉。
所以一定要改变。要么改变自己，要么改变这个大的环境。改变自己，很多人都已
经在做，大家都可以看到有些什么选择。改变环境，则是需要大家一起努力的事了。一
个大胆的想法是，Rock the foundation of biomedical research in the US. 这个制
度存在了这么多年，对美国来说只有好处，他们不会想着为我们谋福利，只有让他们知
道不改变他们要吃亏了，他们才会做出让步。在各大学校和研究机构中的中国研究人员
，粗略统计大致占研究人员的1/5以上，如果有组织的罢工三日，并一起在学校里外游
行一次，这个行动将是规模巨大的，并且一定会被媒体广为报道，对美国将来的police
making产生巨大影响，NIH也将不得不对postdoc工资作出调整。各行各业都可以罢工
，为什么博士后们不可以罢工？经济学告诉我们，组织工会，罢工谋求福利对
unionized labor是有利的，只是对未unionized labor不利，并增加进入壁垒，而这正
是我们想要的。那些热爱科学研究的人们也不必担心这样做损害了科学的发展，从长远
看，这样做提高了科研人员的待遇，一方面可以让他们更安心于试验，另一方面更是可
以减少优秀人才的流失。

这只是一个设想，具体的可行性有待大家讨论，而操作起来更加复杂，得到的改变
更可能会需要相当长的时间。但我相信大家必须要有所行动，为自己争取应得的利益。
我们高中报考的时候，学校为了提高升学率，欺骗学生，抨击热门专业，鼓励学生
报考基础研究的学科。那些城里人资讯发达都不上这个当，农村的学生大多乖乖地跟着
老师走。现在想来，结果就是somehow穷人去干吃力不讨好的行当，富人去干来钱快的
行当。

在上海念研究生的时候，又发现一个有趣的现象。中科院的研究所设在上海，结果
念研究生的又只有极少数的来自上海的。来自上海的，我们都翘拇指，表扬他们有高尚
的情操。其实科研真有比其他行业更高尚吗？大概穷人对于累和苦的活忍耐力比较强吧。

我并不赞同大陆来的学生真有什么一流的水平，一流的分数也不是一流的水平。那
些拿CNS文章敲门的faculty，到头来发现肚子里的货其实很有限。正如我们的奥运金牌
，直接对准目标无限猛练，出成绩快，却并不意味对体育有多热爱，国家的体育有多强
。至于个人的修养，心理素质，表达能力等等，差了不是一点两点。

说到罢工，如果生物postdoc是其他行业，美国人早罢工了。这个在现在看来还是觉
得有点新鲜的创意，说新鲜是因为做研究的基本上比较书呆子气，造反气比较缺。罢工
还有一个好处，警醒后人。但是基本上这个行当是由很多外国人来填充的，美国人转行
的转行，做老板的做老板，个中滋味他们体会不会太深。如果真罢工，美国政府可以提
工资，但是提funding的钱恐怕不现实（生物研究现在的阶段更像烧钱），更可能的情
况是减少职位，减少国际学生和postdoc，增加绿卡申请的麻烦逼你回国，到头来损害
的恐怕还是中国人印度人自己。

生物研究的确需要很多不很smart的劳动力，那些smart的老板需求量不大，所以正
如我以前提倡的，增加工资待遇，极大增加staff scientist的职位（有一定的研究独
立性，待遇与公司的工作相当），减少postdoc的工作年限（比如顶多两轮，6年，现在
的postdoc更像是工作），适当减小规模。

从警示后人的意义来说，相较于罢工，我更倾向于组织两个宣讲团，一个是劝退团，讲
述自己研究生涯的痛苦心得，一个是劝进团，鼓吹21世纪的研究属于生物研究（这个说
法在我看来完全成立，相较于其它学科的基础研究来说），讲述自己研究的乐趣与成就
感。给国内的后来者以知情权，让他们自己鉴别决定。呵呵，说笑说笑……

