* Instar determination using Gaussian mixture model

This is based on Clustering based on statistical Models(chapter 12.5 in the textbook) 

Summary:

Growth of insect nymph is continuous, while the growth of the exoskeleton is not. Heavily sclerotized structures, such as headcapsules, remain approximately the same size during a stadium. The most measurable changes in size occur following molts. These special characters can be used to differentiate instars.
 
Actually the morphological measurements can be viewed as a normal distribution in each instar. Thus, samples from a given population of insects are a mixture of several normal distributions, one for each instar. This assumption is reasonable because measurements from individuals from the same ontogenetic stage are often distributed normally (Sokal & Rohlf 2011). As a result, the instars determination problem can be addressed using Gaussian mixture model.
 
In my program, several characters (head width, pronotum width and length, weight) will be used individually (univariable) or combined (multivariables) in the GMM to get the distribution of each instar.
 
There are R packages (mixtools, mclust) available in CRAN, so I do not implement to algorithms myself.

Weight(body)	Length (Prontum)	Width(Pronotum)	Width(Head)	
