* 申请情况
** 通过什么方式知道了这所学校？
your visit to China. I attended your lecture.
** 是否联系了其它学校或本校的其它老师？
yes. I really contacted with other teachers as well.
** 申请了几个学校？
5
** 如果有其它学校录取了你去不去？
I will accept the offer of Auburn University immediately, if I get it.
** 为什么选择在美国学习？

Actually, I have a good time with Dr.Wang, but I think, in America, the are more marsters, good scientists and 
good educators. Even though I can do some project independently, I still need a marster, a good teacher  
to lead me. 

** 为中美两国教育体制的不同做了那些准备?

I read some articles and novels about the life and education in America. I believe if I observe the rules and 
try my best, I will survive and have good results. The place is not the key point.

** 有没有同学在此学校就读?

I heared of that there was a student of Helin in Aurburn, but I am not sure he is still there.

** 读过我的介绍吗？

Yes, roughly. cockroaches.

* 学习计划及毕业打算

** 在这个学校怎样学习What's your plan in this university?
I am not very familar with  the education system in America. My initial plan is to 

** 希望通过研究生学习获得什么What do you want to receive through the graduate study ?
 the pre-scientist training. the quality to be a real scientist.
** 设想一个特别想弄明白的学术问题，并且设计实验来解决。
I am not kind of genuis, but I really have my ways to solve a problem.In computer science, there is a divde-and-conquer algorithm. I apreciate very much. When I come across a question,
I will figure out what the question is, and then divide it into small parts. I like to sovle it one by one and merge them
together.

** 毕业后的打算What's your plan after you finish your study? What do you plan to do in the future? future career plan

After graduation, I should be a scientist, or entomologist, whaterer it is called. I will find a job at the institute or
the university. I also would  like to be a teacher.

** 是否回国Would you come back to your home country after your study?
I hope I will, but it depends.
** 会在美国找工作吗 Would you like to seek a job in USA?
I am not sure. I will find the place, where I can realize my thoughts.
** 回国的三个理由
***  its my home. 
All the people who bring up me and educate my are in China. I think it the main reason. 
one of my teacher told me that it is my responsibility to make the people around me live a better life.

** 回国后做什么
I like to do somthing researches in evolution. The specific areas depends what I will learn in the Phd stage.
however, one of the areas is clear. Taxonomy or systematics will be part of my rasearch.

** 你认为读PHD的最大困难是什么what will be the biggest difficulty in graduate study?
I read some blogs about how to get a phd degree by a professor of Utah. I agree with him that the bigest difficult
is that you don't believe yourself and can not hold on.

** 愿意做理论还是实验what you like, experimental of analytical?
   both of them are ok. They are all indispensable, but I prefer to do more about theory. 
To find theory from experimental is part of the meaning of experiment.

** 为什么要读PHD?
to get the pre-scientist training. the quality to be a scientist.

** why do you want to be a scientist?
In my view, the scientist is the only one kind of people who don't repeat themself day after day. Everything they do
are new and creative.

* 本科专业以及研究

** 研究兴趣

My interests lie in evolution in the large view. My experience makes me interest in cockroaches.

** 研究经历

*** the biological control.

 I know the procedure to do reseach under the instruction of Dr. Wang.

*** cockroaches raising.

 this is my real contact with cockroaches or insects.

*** the reproduction behavior and structure of cockroaches.

 it is not complete, because I have to do my thesis. I have to put it aside for some time.

*** the classificaion of Blattinae, an family of order blattodea.
 I only identify the species with samples available in our lab. some of the very important literature is
 not in English or Chines. It is in German and Russain. Howerver, I almost done. From my previous experience, I
already know how to distinct diferent family. In the previous stage of the project, I have enough understanding 
about the charcters of the subfamily and genus in Blattinae. In next stage, what I prepare to do is to identify
the different species in the given genus.

** 你现在课题的具体内容，感觉自己有何不足What is your research content now? What is your deficiency?

  I only know English and Chinese. Many literature are not writen in either of them. I don't know much about latin.

** How do you introduce your major to a person who knows nothing about it?
When talk to someone who are curious about my major. I always tell them that I am training to be
 a plant doctor. They know what it is imediately.

** 是否提出过一些特别的观点Do you have any special or excellent idea during your research experience?

almost not. When I find some thing new, I am exicited. however, when I read more books and papers, I find some one 
already find it. it is very common.

**  从以前的工作中学到了什么what did you learn from your past work?

to be patient and do more preparation before you start to talk.
        
how to interact with people and build good relationship.

* 大学及以前经历

** 你怎样学英语How do you study your English?
read books writen in english.

** 本科的学校大吗 ?
yes. very big. almost the bigest in China.

** 本科的大学有多少人多少个系
60000 in 30 college. the number may not be very accurate.

** 学校的排名Where/How does your university rank?
maybe 40-50. I am not very sure.  

** 你的班级排名,年级排名  
top 10, top 30. I am not sure the exact number.

**  GPA为什么低？
 my attitude is not. When entering into college, I didn't put much attention to the grades. 
 I don't spend much time to preparation the exam, especially the unnessary coureses. 

** 学了多少门课/课程名称
I am not sure. many, I think.

** 怎样学习某门课程
learn the basics and do some practice; then do some review.

** 学过某门课程吗？
** 关于课程
Favorite: General entomology
Why: Dr. Wang Jinjun is one of the teacher, who is good scientist and good educator.
最不喜欢的：Introduction to Mao Zedong's Thoughts
Why: Since I don't quite know about politics. The thing in book are unbelievable, at least in my opinion.
学的最不好的： many courses. I think what I learn is not enough. It doesn't have relation to the grades. I may have
a good scroes in a course, but actually I know very little about it.

** Did you use any English textbook in classes?
        Yes. Biostatistics
** Tell me something about your teaching or conduct meeting experience.
after the college entrance examination, I went to a primary school to be a volunteer and teach some courses.
This experience make me want to be a teacher, 
becuse makig others understand you and sharing are very good feelings.

** oral presentation
Yes. in one period, there is an oral presentation in our lab when Dr.Wang was in China.

** What were your best and worst experiences?

The misunderstanding between with me and my friend disappers.
The opposite is my bad experience.     
   
17. Tell me about a time when you experienced a failure. What did you learn from it?
I planed to apply some school in USA and at the same time to prepare the graduate entrance examination in China.
In the end, I give up the preparation to the exam. 
the energy of one person is limited and you have to allocate it properly. you have to concentrate on it.

18. 简历中的细节问题

* 个人品质

** 朋友的对你的评价how do your friends evaluate you?

I don't know. I really have some good friends.
Actually, I have writen an article about my friendship. if you are curious, 
I'd like to send you a copy with the comments from my friends.

** What do you think of your personality?

I really have some friends whose personality is better than me. I am only a ordinary chinese person. Prof. Hu 
may know what does it mean.

** What are your weaknesses? How have you addressed these weaknesses?

I am not good at quick reaction.

** Describe to the representatives who you are: your strengths/weakness, assets, and traits needing development.

reliable，responsible

emotional maturity is not very well，not brave.

** Use three words to describe yourself to others. And why？

Responsible, reliable, ordinary

** Are there any personal circumstances we should know about that you feel strengthen your application?

besieds my major, I have learning much about computer science. I have programming ability.

 Are there any circumstances that you feel might hinder or weaken your application?

I don't have published papers and my GPA is not so high.

** What are you most proud of?
I have some good friends.
** 最牛的事？
I have a phd in the lab do some DNA sequences using perl, a programming language.

** 为什么你值得我们投资investment?
I am one of the best in China in our major, in my view.  I am familiar with cockroaches and contact with them for about two
year.
** 除了学习成绩, 你认为你最大的强项是什么
programming ability. In many cases, we need a computer to help us to do some analysis.
** Have you achieved any achievements?
I think the three month I spend with cockroaches it the first big achievements in my life.
Maybe, it is ridiculus.
** How do you define success? 
 have a good relationship with others and make others happy.

** How do you release your work stresses? 
read some novel or change the work you do.
** What will you do if the professor let you do what you can't do?
If I think no one can make it,I try to explain and conviced that no one can really make it.
if there is any possible, I will try to do it.       
** Do you have something you can't complete?
yes. the project about the rotation of ootheca. I think it is impossible at the moment. If there are more
equipment available, Maybe it can be. After Dr.Wang return, we will continue it.
** How do you define teamwork？
play your part well and keep an eye on the large picture.
** What sort of team work experiences have you had in the past? 
all the works in the lab is team work. all the members in the lab can give me advice and they often do so.
** What sort of role do you most often assume in a team work situation? 
I always try to be a leader. 
12．How about your abblity to be a teaching assistant?
It's no problem if use Chinese, but I need some practice in English.
I am trying to be an educator.
** Explain in further detail about extra curricular activities or professional accomplishments.
not very much. most of my free time are spending in reading blogs or novels.
* 个人问题
** Tell me about your family.
both of my parents are ordinary famers. I am influenced by my parents greatly. 
        
** Who is the great person in the world in your eyes?
  There are many persons I should learn from, but I do not believe there is no so-called greatest person. 
** 是否爱运动
not very much

* 社会政治经济问题的观点
** 中国的独生子女政策What do you think of the only child policy of your country? 
** 你对美国当今社会的认识.        
** 你对恐怖主义有什么认识?
** 问我对三峡大坝的看法
** 你认为中国的教育体制怎么样? 如果你是胡锦涛,也就是你手中有了一个power,你将如何解决中国的教育问题?
        
* 无聊
** 你们学校什么时候放假When is the vacation of your University?   Jan. 17
** 天气                      
** 现在是北京时间几点？
   
* Do you have any question to ask me?

** when the decision is made?
** The project you are doing now?
** If admitted, what should I prepare for entering and your group?
** if I am admited, Can I choose the project freely in an target areas or the define project?
** Do you have any project with china? or Will you cooperate with SWU in the furture?


* 客套话
* "Please speak loudly for my phoneline is not clear" 
* 最后的时候，一定要thanks for calling。而且打完电话之后，还要跟上一封email。
* 如果有问题回答不出来的，你可以跟他说，I have no idea of it now. Can I reply you later by email?
* Thank you for giving me this opportunity
* 如果没听懂对方的问题，不要不懂装懂，请求pardon。尽可能表现的有礼貌，有问必答，而不要答非所问
