Insect Morphology
#+OPTIONS: toc:nil 
* The abdomen
** Regions of the Abdomen
*** Primary and Secondary Segmentation. 
The abdominal regions usallly referred to as segments are more
appropriately called scleromata since the functional conjunctivae are memebranous
 parts of primitive somites. The scleromata regularly overlap posteriorly.
**** Prgenital or visceral segement(I-VII).
These segments contain the principal viscera.
**** Genital segments(VIII and IX)
These segments bear the openings of the genital ducts.
**** Postgenital segments(X and XI)
** Sclerites of an abdomenal scleroma
*** there are only two, the tergum and the sternum
** Number of Segments in Adults
*** General
**** There are never more than 11 scleromata.
**** The direction of evolution has been more toward reduction than increase in the numbre of scleromata
**** Reduction is ususally at the posterior end, but in higher orders, the first and second tend to be reduced.
*** Postgenital area
**** The 10th scleroma.
*****  This is present as a complete independent annulus in some.(Thysanura, Odonata,Ephemeroptera,Dermaptera, Homoptera, Plecoptera)
*****  In others the sternum is membranous and not visible externally.(Embioptera, Blattodea, Orthoptera)
**** The 11th scleroma. 
This represents the last true somite since the 12th  the periproct (telson) (Crustacea).
***** In Protura
the 11 scleroma is a normal annulus with tergal and sternal portions.
***** In other insects
 this is reduced to a dorsal or tergal plate called the epiproct and 
two ventrolateral plates called paraprocts, which are remnants of the sternum,
as in the Acrididae and the Gryllidae.
***** It is entirely supressed in all Endopterygota
As a result, body ends with the 10th scleroma.
*** The periproct (telson). 
This is the so-called 12th segment of authors. It bears the anus.
**** In Crustacea.
It is the telson of the adult
**** In Protura
It is the 12th segment, which are sometimes therefore called "telson tails".
The Protura undergo anamorphosis.
**** In other insects.
It is represented only as a circumanal membrane at the end of segment XI, as in Odonata.
*** Genital segemts.
These are the segments pricipally involved in the formation of the copulatory organs or
"external genitalia". In the male, this is segment IX. In the female there are segments VIII and IX.
** Sprialces
*** Position within the segment
Spricles arise from the lateral parts of the dorsum of the body segments just above the limb bases. The pleuron,
however, may secondarily grow up around the spiracles.
*** Numbers.
Possible positions on segments or total numbers for all stages.
**** Labial segment
one pair in the labial segment of the embryo.
**** Prothorax
Prothorcic spriacles are present in the embryo of some insects, but not in the adult. The single pair in the cervix of Collembola might
belong to the labial segment.
**** Mesothorax
One pair in all insects except Diplura, some of which have two pairs.
**** Metathorax
One pair in all insects except DIplura, some of which have two pairs.
**** Abdomen 
The maximum number in adults is eight pairs, but this number is reduced in many.
* Abdomen appendages
** Cerci
*** These are true appendages of segments XI.
*** They are borne between the epiproct(tergum XI) and the paraproct(lateral plate of segment XI).Their muscles, modified longitudinal dorsal muscles, arise on tergum X.
*** Fuctions.
**** Usually tactile.(silverfish)
**** Part of the male genitalia(clasping structures) in caddisflies(Trichoptera)
**** Weapons of defense.(Dermaptera)
**** Breathing tube (Nepidae)
*** Abdomenial extension?
**** larva of rat-tailed maggot.(Syrphidae)
* The tergum of the thorax
** The Pterothorax.
*** Phragmata
A phragma is a plate-like lobe of any of the antecostae 
of the mesonotum, metanotum, and 1st abdominal tergum.
 These phragmata are plate-like expansions developed for 
attachment of the flight muscles.

**** First phragma
 the expanded antecosta of the mesothorax; 
**** Second phragma
 the antecosta of the metathorax; 
**** Third phragma 
 the antecosta of the 1st abdominal segment. 
*** Postnota (postscutella of authors).
****  Postnotum (phragmanotum) 
the phragma-bearing plate, often present in the dorsum of a wing-bearing segment, derived from the anterior part of the following tergum (Snodgrass Fig. 98); distinguished from the alinotum, the wing-bearing plate of the notum (Snodgrass Fig. 96).
**** The conjunctivae of the alate segments are usually reduced or entirely eliminated.
 The postnotum, which in position is the last sclerite of the segment, is actually the greatly expanded acrotergite of the scleromata that follow (Snodgrass Fig. 98; Snodgrass Fig. 96; Snodgrass Fig. 36).

****  Number.

***** The mesothorax may bear one postnotum.
 It is the acrotergite of the metathorax 
***** The metathorax may bear one postnotum.
 It is the acrotergite of abdominal segment 

