笔记本
** [2011-01-09 周日 10:47]  模版的配置文件如下：

   (setq org-remember-templates
       '(("TODO" ?t "* TODO %?\n %x\n %a" "~/doc/org/home.org" "Tasks")
	 ("IDEA" ?i "* IDEA %?\n %i\n %a" "~/doc/org/home.org" "Idea")
	 ))
** [2011-01-09 周日 16:07]  factor 学习

** factor 基本词汇
drop 清空当前栈
.    打印当前栈，然后清空
** [2011-01-10 周一 10:42]
** [2011-01-10 周一 10:55]  Dorylaea
Rehn,1933 Duchailluia
Bei-Bienko,1965
Bei-Bienko,1969
Bei-bienko,1938 Hebardina

Hanitsch, 1950
Shiraki,1931
Asahina,1985
Rehn & hebard, 1927
Princis,1966 
Bei-bienko,1957
??? Pelmatosilpha
??? Pseudoderopeltis
???Scabinopsis Bei-Bienko,1969
Thyrsocera Burmeister, 1838
** [2011-01-11 周二 13:49]  Tergite eingesenkt und lateral aufwä
Tergites sunk upwards and laterally
** [2011-03-20 周日 23:06]  怎样交换行列？

  
  [[file:c:/Users/echo/Documents/R/egghdate.csv]]
** [2011-03-26 周六 17:11] 

做图标来说明蜚蠊研究状况。

 
 [[file:c:/Users/echo/org/cockroaches.data::species%20scorteccii%20Princis%201960][file:c:/Users/echo/org/cockroaches.data::species scorteccii Princis 1960]]
** [2011-03-27 周日 15:27] R 绘图
par(mar = c(4, 4, 4, 4), xaxs="r")

 plot(dat$year,dat$species,asp=10,type="h")

 
 [[file:c:/Users/echo/Documents/perl/perlwares/target.txt]]
** [2011-03-27 周日 17:03] 把for结构写反会怎么么样？
** [2011-03-27 周日 17:04]
use strict;
use warnings;
use Data::Dumper;
my @lines;
my @line;
while (<DATA>){
chomp;
@line=split /,/ ;
push @lines, [@line];
}
my $var=@lines;
print $var;
print Dumper @lines;
my $i;
for($i=0,$i++,$i<$var){
    print $i;}

print "================";


my $j;

for($i=0,$i++,$i<@lines){
    print $i;
    print Dumper @{$lines[$i]};
    for($j=0,$j++,$j<@{$lines[$i]}){
	print $j;
	print "$lines[$i][$j]";}
print "\n";
}

#print Dumper @lines[$i];

__DATA__
0.107,0.105,0.104,0.104,0.106,0.102,0.106,0.098,0.097,0.094,0.092,0.089,0.083
0.115,0.111,0.112,0.107,0.106,0.106,0.107,0.099,0.097,0.099,0.095,0.089,0.090
0.149,0.147,0.146,0.145,0.143,0.142,0.141,0.143,0.139,0.135,0.137,0.127,0.122
0.144,0.146,0.143,0.140,0.136,0.134,0.135,0.129,0.129,0.123,0.120,0.113,0.111
0.150,0.151,0.148,0.146,0.144,0.141,0.137,0.134,0.131,0.128,0.126,0.107,0.099
0.141,0.141,0.137,0.139,0.140,0.138,0.140,0.140,0.134,0.132,0.131,0.130,0.129
** [2011-03-27 周日 19:50] perl program
print "give me a pattern,please\n";
$line=<STDIN>;
if ($line =~/^\s*$/){
print "you give me nothing,goodbye!";

}else{
    chomp($line);
    while($line){
    print "I saw $_";
}

}
why is it running all the time?

 
 [[file:c:/Users/echo/Documents/perl/dir.pl::print%20give%20me%20a%20pattern%20please%20n][file:c:/Users/echo/Documents/perl/dir.pl::print give me a pattern please n]]
** [2011-06-08 周三 22:00] inner core

*** what do it mean to be a well-rounded student at an American University today?
*** 学校提供交流的空间，相互交流。
** test
** [2011-07-10 周日 17:08] 昆虫真菌

*** 昆虫寄生真菌
　　kunchong jisheng zhenjun
　　昆虫寄生真菌
　　entomogenous fungi
　　因对昆虫的寄生性而组成的一个独立的生态群。以昆虫为基质的腐生真菌和仅生活在昆虫菌巢内的虫道真菌都不属于此类。
　　按寄生方式，昆虫寄生真菌可分为4类：

*** 外部寄生类　

寄生在昆虫体表的真菌。绝大多数属于的虫囊菌目，少数为半知菌类。一般不能人工培养。大多数虫囊菌以脚胞固着在昆虫的外壳上，但不进入体内。也有一些虫囊菌没有脚胞，以吸胞进入寄主体内，有时吸胞可在虫体内茂密地分枝多次，但对寄主为害不大(见)。
*** 内部寄生类　

能侵入昆虫体内并常使昆虫死亡的真菌。重要的有雕蚀菌属、虫霉属、干尸虫霉属、虫草属、白僵菌属、绿僵菌属、座壳孢属、多毛孢属等。除雕蚀菌属和虫霉属的许多种还不能人工培养外，其他内部寄生菌都可人工培养。对寄主的侵染可从外壳、口部、呼吸管等进入。直接穿透寄主外壳的真菌往往有分泌壳质酶水解昆虫外壳壳质的能力。此外，昆虫吃食时带入肠道的真菌孢子也可以发育成为内部寄生菌。昆虫内部寄生菌以游动孢子囊、菌丝体、菌丝断片、酵母状细胞、孢子等各种方式在虫体内繁殖。染病的昆虫在临死前爬向高处，这有利于昆虫死后病菌孢子的传播。内部寄生真菌,特别是子囊菌,往往是在寄主死后才形成孢子；一些低等真菌，如雕蚀菌属、虫霉属和和团孢属，可在寄主死前形成孢子。　　
*** 捕食类

具有捕捉土壤变形虫、线虫等原生动物的特殊功能并进行寄生的真菌。主要属于捕虫霉目和半知菌的丛梗孢类(见)。
*** 局部共生类　

能侵入昆虫体腔但仅限于局部器官，而且与昆虫形成共生关系的真菌。如隔担菌属、等。广泛寄生于蝗虫、蚜虫、金花虫等科的球孢白僵菌是有效的生物防治用真菌，主要寄生于鞘翅目和同翅目的金龟子绿僵菌也是有潜力的生物防治用真菌。但寄生于蜜蜂、家蚕等的真菌则为害菌。此外，真菌寄生于昆虫还能形成著名的中药，如僵蚕、冬虫夏草。
** [2011-07-29 周五 13:33] 选课

Course selection


Dear Prof. Hu,

I think the following courses is suitable for me.

Appointment

Dear Prof. Appel,

I am Hao Wu. I arrived at Auburn in July 28.

I want to know when you are available, so we can talk about the future program and get familiar with the lab.

Thank you.

With best wishes,

Hao Wu
** [2011-08-02 周二 10:49]
** [2011-08-24 周三 21:19] Distributions

Binormal, Poisson, normal, chi-square, t and F distribution
** [2011-09-15 周四 21:49] age-grading

knowing the number of instars for each mayfly species or population could lead to a better understanding
of the biology of mayflies. The large number of nymphal molts characteristic of mayflies offers the possibility of closely charting
development and thereby correlating development with environmental factors on a fine scale.

various criteria for determing instar have been 
proposed--precise measurement(Beck 1983) or visual
aproximation (Dittrick & Chiang 1981) of head capsule
width, measurement of prothoracic shield(Caffrey &
Worthley 1927), and numbering the successive molts of 
larvae reared individually in the laboratory(Beck 1950, Matteson & Decker 1965)
** [2011-12-18 Sun 14:35] 常见昆虫俗名
常见昆虫和蜱螨：名称及简述


 
常见昆虫和蜱螨
 
1.       【昆虫】 insects又称六足虫。节肢动物门昆虫纲（Insecta）。体分头、胸、腹3部分。头部具触角一对。胸部分为前胸、中胸和后胸3节，每节有一对足。通常中、后胸各有一对翅，分别为前翅和后翅。陆生或水生。世界上分布最广、种类最多的动物类群。
 
2.       【原尾目】 Protura通称原尾虫。最原始无翅小型昆虫。无触角和复眼。前足特长，有触角的功能。口器内藏，适于刺吸。喜潮湿，常生活于落叶腐殖质中及树皮、砖石下。分布世界各大陆。
 
3.       【原尾虫】 proturans 原尾目的通称。
 
4.       【弹尾目】 Collembola通称跳虫。原始无翅小型昆虫。无复眼。腹部有叉状弹器及黏管，能跳跃。多生于潮湿环境，食性复杂。有些种类为农作物和园艺害虫。世界性分布。
 
5.       【跳虫】 springtails弹尾目的通称。
 
6.       【双尾目】 Diplura通称双尾虫、铗尾虫。原始无翅小至中型昆虫。体型细长。白或灰色。触角念珠状。无眼。口器适宜咀嚼。尾须发达，线状或钳状。栖息地下，畏光。世界性分布。
 
7.       【双尾虫】 campodeids双尾目双尾虫科（Campodeidae）的通称。尾须丝状，与触角等长或更长，多节。
 
8.       【铗尾虫】 japygids双尾目铗尾虫科（Japygidae）的通称。尾须铗状，不分节。
 
9.       【缨尾目】 Thysanura原始无翅小至中型昆虫。触角长，丝状。口器适宜咀嚼。通常有复眼。体被鳞片。具一对尾须和一条中尾丝。有些种类如衣鱼是重要的家庭害虫。世界性分布。
 
10.    【衣鱼】 silverfish又称蠹鱼。缨尾目衣鱼科（Lepismatidae）的通称。体长而扁，有银色鳞片。复眼小；无单眼。常生活于室内衣物和书籍中，啮食其上的浆糊和胶质物。
 
11.    【石蛃】 bristletails缨尾目石蛃科（Machilidae）的通称。体长纺锤形或圆柱状，有鳞片。复眼大；有单眼。能跳跃。生活在森林草地、山地岩礁上和白蚁巢中，食干或腐烂的植物质。
 
12.    【蠹鱼】 silverfish即衣鱼。
 
13.    【蜉蝣目】 Ephemeroptera通称蜉蝣。小至中型昆虫。体柔软，细长。复眼大。翅膜质多褶，后翅小或无。有两条细长尾须。幼期水生。成虫寿命短者数小时，长者数天至周许。世界性分布。
 
14.    【蜉蝣】 mayflies 蜉蝣目的通称。
 
15.    【蜻蜓目】 Odonata俗称蜻蜓、豆娘等。中至大型昆虫。头大，活动自如。口器适宜咀嚼。翅膜质透明，脉序网状。幼期水生，肉食性，俗称水虿。广布全球，尤以热带为多。
 
16.    【蜻蜓】 dragonflies蜻蜓目差翅亚目（Anisoptera）的通称。体型较大。头部复眼连接。后翅稍大于前翅；翅基不呈柄状。停息时翅展开，平放两侧。
 
17.    【豆娘】 damseflies又称蟌。蜻蜓目束翅亚目（Zygoptera）的通称。体细弱。头部复眼分离。前、后翅相似，翅基缩小呈柄状。停息时翅竖立在背上。
 
18.    【蜚蠊目】 Blatteria通称蜚蠊、蟑螂。中至大型昆虫。身体扁平，多黑褐色。头小。触角长，丝状。前翅革质，后翅膜质。畏光喜暗。有的种类可传播疾病。多分布热带。
 
19.    【蜚蠊】 cockroaches 蜚蠊目的通称。
 
20.    【蟑螂】 cockroaches 蜚蠊目的通称。
 
21.    【地鳖】（Eupolyphaga sinensis） 又称土鳖。蜚蠊目地鳖科（Polyphagidae）。体扁平卵圆形，长20～30毫米，棕黑色而带光泽。头小。触角丝状。复眼发达。雄虫有翅，雌虫无翅。杂食。昼伏夜出。可药用。广布，多分布热带和亚热带。
 
22.    【螳螂目】 Mantodea中至大型昆虫。头三角形。前胸延长。前足为捕捉足，腿节和胫节有可对合的刺列。前翅革质，后翅膜质。肉食性。卵鞘可入药。主要分布热带。
 
23.    【螳螂】 mantids螳螂目的通称。
 
24.    【等翅目】 Isoptera通称白蚁。小至中型昆虫。触角念珠状。口器适宜咀嚼。有翅或无翅。有翅种类前后翅相似，膜质狭长。为营巢生活的群栖社会性昆虫，有蚁后、工蚁、兵蚁等型，可对建筑物和堤防造成破坏。多分布热带和亚热带。
 
25.    【白蚁】 termites等翅目的通称。
 
26.    【缺翅目】 Zoraptera通称缺翅虫。较原始昆虫。体小型，柔软。头大，活动自如，口器适宜咀嚼。胸部各节近等。无翅或有翅。种类稀少，分布较温暖地区，西藏东南部发现有分布。
 
27.    【缺翅虫】 zorapterans缺翅目的通称。
 
28.    【中华缺翅虫】 Chinese zorapteran（Zorotypus sinensis）缺翅目缺翅虫科。缺翅型体长3～4毫米，深褐色。触角念珠状，9节。1973年首次发现于西藏察隅地区。
 
29.    【襀翅目】 Plecoptera通称石蝇。较原始有翅昆虫。体扁软，具长丝状触角和尾须。口器适宜咀嚼。翅膜质。若虫水生，有成簇的丝状鳃，肉食性或草食性。世界性分布。
 
30.    【石蝇】 stoneflies襀翅目的通称。
 
31.    【竹节虫目】 Phasmida通称竹节虫、樇。中至大型昆虫。体型呈竹节状或叶片状，颜色多为与栖息环境相似的绿色或褐色。头小，口器适宜咀嚼。多分布热带和亚热带。
 
32.    【竹节虫】 stick insects 竹节虫目的通称。
 
33.    【叶樇】 leaf insects又称叶子虫、叶樇。竹节虫目叶樇科（Phyllidae）的通称。体扁，绿或褐色，形如叶片。分布热带和亚热带。
 
34.    【杆樇】 little sticks又称竹节虫。竹节虫目杆樇科的通称。体细长，绿或褐色，缺翅，形如竹节或树枝。多分布于热带和亚热带。
 
35.    【蛩蠊目】 Grylloblattodea通称蛩蠊。较原始昆虫。体扁长型。触角长丝状。口器适宜咀嚼。无翅。夜出活动。多栖息于海拔1200米以上高山和高纬度冷湿地带。种类稀少，分布东亚和北美西部，吉林长白山有分布。
 
36.    【蛩蠊】 grylloblattids蛩蠊目的通称。
 
37.    【中华蛩蠊】 Chinese grylloblattidGalloisiana sinensis。蛩蠊目蛩蠊科（Grylloblattidae）。体长12毫米，棕黄色。触角丝状，34节。1986年首次发现于吉林长白山。
 
38.    【直翅目】 Orthoptera俗称蝗虫、螽斯、蟋蟀。中至大型昆虫。口朝下，口器适宜咀嚼。前翅革质；后翅膜质，停息时呈扇状折叠于前翅之下。少数无翅。后足腿节粗壮，适于跳跃。雄虫一般有发音器。一些为重要的农业害虫。世界性分布。
 
39.    【蝗】 locusts 直翅目蝗科（Acrididae）的通称。身体细长，绿色或黄褐色，适于在杂草和灌丛中活动。雄虫能以后足腿节摩擦前翅而发音。幼虫称蝻。主要危害禾本科植物，食量大，为重要的农业害虫。
 
40.    【蚱】 pigmy grsshoppers 直翅目蚱科（菱蝗科）（Tetrigidae）的通称。体小型，呈菱形。触角甚短。前翅退化成鳞片状；后翅发达。少数种类无翅。无听器和发音器。喜潮湿，以菌类、苔藓和杂草种子等植物或腐败物为食。
 
41.    【蜢】 monkey grsshoppers直翅目蜢科（短角蝗科）（Eumastacidae）的通称。体细，近圆筒形。触角短丝状,近端部有一个小突起。前、后翅发达或缺如。无听器和发音器。
 
【飞蝗】1 migratory locusts 直翅目蝗科斑翅蝗亚科（Oedipodinae）的通称。体较粗大，腹面常具细密绒毛，绿色或黄褐色，适于在杂草和灌丛中活动。常大量发生，长距离迁移，对农业危害较大。2 migratory locust特指飞蝗Locusta migratoria。根据生活习性，分为群居和散居两大类型，两者可互相转化。群居型可行集群迁飞，是重要的农作物害虫。
 
42.    【东亚飞蝗】 oriental migratory locust直翅目蝗科。分布亚洲温暖地区及中国东部广大平原地区，严重危害禾本科作物。中国历史上的蝗灾，多由东亚飞蝗造成。
 
43.    【稻蝗】 Chinese rice grasshopper 又称中华稻蝗（Oxya chinese）直翅目蝗科。成虫黄褐色，雄虫体长16～40毫米，雌虫比雄虫大约1倍。以危害水稻为主的多食性害虫。广布于亚洲、澳大利亚和毛里求斯。
 
44.    【竹蝗】 bamboo locusts直翅目蝗科竹蝗属（Ceracris）的通称。主要分布于东洋区。中国常见种类黄脊竹蝗（C. kiangsu），在华东、华南及西南均有分布，为竹林重要害虫。
 
45.    【蟿螽】 Chinese short-horned grasshopper又称中华蚱蜢（Acrida chinensis）。直翅目蝗科。体长形，绿或黄色。头顶明显向前突出，触角短，剑形。后足长，善跳跃。广布华中、华南和西南。
 
46.    【螽斯】 long-horned grasshoppers 直翅目螽斯科（Tettigoniidae）的通称。体纵扁或近圆柱状。触角长丝状。有翅或无翅。雄性靠前翅相互摩擦发声。有翅种类栖息于草丛间；无翅种类多穴居。肉食或杂食性。
 
47.    【纺织娘】 cane long-horned locust 又称蔗点翅螽（Mecopoda elongata）。直翅目螽斯科。体长50～70毫米，绿或褐色。鸣声如“轧织，轧织”而得名。可为害桑树。分布东南沿海各地。
 
48.    【灶马】 camel cricket（Diestrmmena unicolor）直翅目蟀螽科（Gryllacridae）。体粗短，背驼。触角极长。翅退化。后足发达，适宜跳跃。穴居。是屋内灶前常见的昆虫。
 
49.    【蟋蟀】1crickets 直翅目蟋蟀科（Gryllidae）的通称。体小至中型，黑褐或黄色，背腹稍微扁平。触角长丝状。有听器。穴居于地表、土中或砖石下。多杂食性。
2 Chinese cricket 特指中华蟀（Gryllus chinensis），又称促织、蛐蛐。直翅目蟋蟀科。体长20～40毫米。头圆。胸宽。善鸣，好斗。雄虫昼夜发出鸣声。可入药。农业害虫。中国大部分地区分布。
 
50.    【灶马蟀】 Indian house cricket（Gryllodes sigillatus）直翅目蟋蟀科。体淡黄。翅短。鸣声细而高，以“凄哩凄哩……”连续发出。常见于室内外。
 
51.    【油葫芦】 field cricket （Gryllus testaceus）直翅目蟋蟀科。体黑褐色，有油光。白天藏于杂草、砖石、土块下及田间裂缝中，夜出活动。成虫有筑穴习性。雌雄同穴。杂食性。广布中国及印度、马来西亚。
 
52.    【金钟儿】（ Homoeogryllus japonicus） 又称马铃。直翅目蟋蟀科。体黑色，广扁，瓜子形。长19毫米。鸣声“铃铃……”。分布中国、日本和东南亚各地。
 
53.    【蝼蛄】又称土狗子、蝼蝈。mole crickets直翅目蝼蛄科（Gryllotalpidae）的通称。体圆柱形，被绒状细毛。头尖。前足胫节粗大，适于掘土。以土栖为主。有趋光性。杂食性，危害植物根茎。
 
54.    【纺足目】 Embioptera通称足丝蚁。长形软体昆虫。生活在丝质网状甬道内。口器适宜咀嚼。雄虫有翅，雌虫无翅。前足第一跗节膨大，有纺丝腺，能泌丝结网。有群居性。分布世界温暖地区。
 
55.    【足丝蚁】 embiids  纺足目的通称。
 
56.    【重舌目】 Diploglossata 小型昆虫。体扁平,长8～10毫米。口朝下，口器适宜咀嚼。触角丝状。前胸大于中、后胸。无翅。腹端有一对不分节的尾须。外寄生于鼠类体上。主产于非洲。
 
57.    【鼠螋】 hemimerids重舌目鼠螋科（Hemimeridae）的通称。鼠体外的寄生虫。成虫体小扁平，长8～10毫米。眼退化。尾须细长，不分节。食寄主表皮物质。
 
58.    【革翅目】 Dermaptera通称蠼螋。小型昆虫。体狭长而扁，表皮硬化。口朝前，口器适宜咀嚼。前翅小，革质；后翅大，膜质，停息时折叠于前翅下。身体末端有尾铗。杂食性。雌虫有护卵育幼的习性。分布热带至温带。
 
59.    【蠼螋】 earwigs革翅目的通称。
 
60.    【蝠螋】 bat earwigs 革翅目蝠螋科（Arixeniidae）的通称。体扁，小型，缺翅，有毛。生活在热带蝙蝠体上和洞内，为外寄生性或穴居性昆虫。
 
61.    【同翅目】 Homoptera小至中型昆虫。包括蝉、介壳虫和蚜虫等。口器适宜刺吸，喙由头下后方或前足基部间伸出。翅膜质或近革质。有翅或无翅。多有蜡腺。植食性，刺吸植物汁液，有的是重要的农业害虫。世界性分布。
 
62.    【蝉】 cicadas 同翅目蝉科（Cicadidae）的通称。复眼突出，单眼3个，呈三角形排列。触角短鬃状。翅膜质，脉纹粗。雄性多具发音器。若虫的蜕皮称蝉蜕，被真菌寄生时可形成蝉花，均可入中药。
 
63.    【蟪蛄】 Platypleura kaempferi同翅目蝉科（Cicadidae）。体长20～25毫米，紫青色，有黑纹。后翅除外缘外均为黑色。五六月作“吱…吱吱”的鸣声。危害桃、梨、李桑、茶等。中国广布，亦见于日本、菲律宾。
 
64.    【蚱蝉】 black cicada又称黑蚱蝉（Cryptotympana atrata），俗称知了。同翅目蝉科。体长约43毫米，黑色有光泽。雄性有发音器，夏日鸣声很大。蜕可药用。分布长江以南，亦见于美洲、澳大利亚和东南亚。
 
65.    【蛁蟟】1 （Oncotymapana maculaticollis）又称雷鸣蝉、鸣鸣蝉。同翅目蝉科。体长35～37毫米，体黑而有鲜绿斑纹。有发音器，昼鸣，夕刻不鸣。分布中国北方。
 
2 （Meimuna mongolica ）同翅目蝉科。体背灰褐色。头有黑边，腹部有暗赤褐色盘状纹。上海一带较常见。
 
66.    【飞虱】 planthoppers同翅目飞虱科（Delphacidae）的通称。小型善跳昆虫。后足胫节末端有一大形可动的端距。同一种常有长翅型和短翅型两种类型。多危害禾本科植物，有的是重要的水稻害虫。
 
67.    【稻飞虱】 rice planthoppers同翅目飞虱科为害水稻种类的通称，俗称蠓虫。主要种有褐飞虱和白背飞虱。
 
68.    【叶蝉】 leafhoppers同翅目叶蝉科（Cicadellidae）的通称，又称浮尘子。体小型，狭长，色彩艳丽。后足胫节有1～2列短刺。危害禾谷类、蔬菜、果树和其他林木。
 
69.    【浮尘子】狭义上为同翅目叶蝉科的通称，广义上还包括同翅目飞虱科。
 
70.    【稻叶蝉】 rice leafhoppers同翅目叶蝉科为害水稻种类的通称，又称稻浮尘子。主要种有黑尾叶蝉和白翅叶蝉。
 
71.    【蜡蝉】 fulgorid planthoppers同翅目蜡蝉科（Fulgoridae）的通称。体色鲜艳，中至大型。头额部向前延伸如象鼻。有些种类体上覆有粉状物质或蜡质丝状物。主要分布热带及亚热带。
 
72.    【樗鸡】 Lycorma delicatula 又称灰蝉、红娘子、斑衣蜡蝉。同翅目蜡蝉科。体长14～22毫米。前翅基部淡褐色而稍带绿色，有黑斑20余个，端部黑色，脉纹白色；后翅基部鲜红色，有黑斑7～8个，中部有一白带，翅端黑色。体翅常覆有粉状白蜡。危害臭椿、榆等。
 
73.    【沫蝉】 spittlebugs 同翅目沫蝉科（Cercopidae）的通称，俗称吹泡虫、吹沫虫。体长小至中型。后足胫节具1～2粗刺，端部有一群小刺。若虫常覆埋在肛门喷出的泡沫中，受到防护。多数危害木本植物。
 
74.    【吹沫虫】 spittle insects 同翅目沫蝉科的俗称。
 
75.    【木虱】 suckers 同翅目木虱科（Psyllidae）的通称。体小型，形似小蝉，善跳，多为绿色或黑褐色。若虫扁平，宽卵形，常聚集取食。有的种外被蜡质，有的在叶上形成虫瘿。
 
1.       【桑木虱】 mulberry suckers （Anomoneura mori）同翅目木虱科。体长3～4毫米。触角黄褐色，末端黑色。胸部有污黄色或灰白色条纹。前翅半透明，多暗褐色斑点。若虫常分泌白色蜡毛。危害桑树。
 
2.       【粉虱】 whiteflies 同翅目粉虱科（Aleyrodidae）的通称。体小型，长1～3毫米，常被有白色蜡粉。若虫形似介壳虫，扁卵圆形，常分泌白色蜡质。一些种类为柑橘害虫。
 
3.       【蚜虫】 aphids 同翅目蚜总科（Aphidoidea）的通称，又称腻虫、蜜虫。体小而软。触角3～6节。腹部末端常有腹管。有翅或无翅。其排泄物富含糖分，俗称蜜露。有性或无性生殖。以刺吸植物叶汁为生，危害农作物和其他植物。
 
4.       【棉蚜】 cotton aphid（Aphis gossypii）俗称瓜蚜。同翅目蚜科。有翅或无翅。无翅胎生雌蚜体长1.2～1.9毫米；有翅胎生雌蚜体长2.0毫米。杂食性。世界性棉花和瓜类重要害虫。
 
5.       【桃蚜】 green peach aphid（Myzus persicae）又称烟蚜。同翅目蚜科。有翅或无翅。有翅胎生雌蚜红褐色。无翅胎生雌蚜体绿色。危害烟草、果树及十字花科蔬菜。世界性温室害虫。
 
6.       【五倍子蚜】 Chinese gall aphid （Schlechtendalia chinensis）同翅目瘿绵蚜科。有翅型体长1.5毫米，无翅型体长1.1毫米，淡黄褐或暗绿色。寄生于盐肤木等树木上，形成虫瘿，称五倍子，为工业和医药重要原料。产于亚洲东部及北美。
 
7.       【苹果绵蚜】 woolly apple aphid（Eriosoma lanigerum）俗称绵虫。同翅目瘿绵蚜科。有翅或无翅。有翅胎生雌蚜成虫体长1.8～2.2毫米，无翅胎生雌蚜体长1.9毫米。体被白色蜡质绵毛。危害苹果、沙果、海棠等。重要检疫害虫。
 
8.       【甘蔗绵蚜】 sugarcane wooly aphid（Ceratovacuna lanigera）又称甘蔗粉蚜。同翅目扁蚜科。有翅或无翅，体被蜡粉。无翅成虫为黄褐、灰褐、黄绿等色；有翅成虫黑色。甘蔗重要害虫。分布亚洲和大洋洲。
 
9.       【吹绵蚧】 cottony cushion scale（Icerya purchasi）又称吹绵介壳虫。同翅目绵蚧科。雌成虫椭圆形，体长5～6毫米，橘红色有黑色短毛，覆白蜡粉。雄成虫体长约3毫米，橘红色，触角黑色。世界性果木害虫。
 
10.    【紫胶虫】 lac insect（Laccifer lacca）同翅目胶蚧科。雌虫呈萝卜形或梨形，黄褐色至紫红琥珀色；雄虫呈长梭形，鲜朱红色。雌虫分泌物紫胶是重要的工业原料。原产印度和东南亚。中国已在北纬24度以南各地推广种植。
 
11.    【介壳虫】 scale insects同翅目蚧总科（Coccoidea）的通称，又称蚧。雌雄异型。雌虫无翅，足退化，体各部愈合，营固着生活。雄虫前翅膜质，后翅转化为平衡棒。体常覆有蜡粉或介壳。寄生于植物枝干和叶部，许多是林木重要害虫。                                                                             
 
12.    【蚧】 soft scales即介壳虫。
 
13.    【胭脂虫】（Coccus cacti）同翅目蚧科。母体成熟后僵化，固着于树枝。幼虫在其僵体内孵化，长成后破体壁而出。生产胭脂的原料。在仙人掌上繁殖，每年可收获两次。产于中国及欧洲、美洲。
 
14.    【白蜡虫】 white wax scale（Ericerus pela）同翅目蚧科。体小，雄虫有翅或无翅，雌虫无翅，长卵形或稍扁。多寄生于女贞和白蜡树上，雄虫分泌白蜡，包围体躯。白蜡为工业和医药重要原料。中国特有种，分布秦岭以南各地。
 
15.    【龟蜡蚧】 Florida wax scale（Ceroplastes floridensis）同翅目蚧科。雌虫蜡壳椭圆形，表面呈龟甲状凹陷，周围有8个粗糙突起，直径3～4毫米。若虫经固定后，在叶部及嫩梢上吸取汁液。柑橘、柿、梨和茶等果木害虫。分布北半球。
 
16.    【红蜡蚧】 red wax scale（Ceroplastes rubens）又称红蜡介壳虫。同翅目蚧科。雌虫蜡壳长3～5毫米，红色，半球形，中央凹陷似脐状，四角各有一条白蜡带。雄虫体暗红色。多聚集于树干及嫩枝上吸食汁液。世界性果木害虫。
 
17.    【半翅目】 true bugs通称蝽、椿象。小至大型昆虫。体多呈扁平。口器适宜刺吸，自头前端伸出。前翅基半部坚硬，革质，端半部柔软，膜质；后翅膜质。多有臭腺，可分泌臭椿气味。植食性和捕食性。世界性分布。
 
18.    【蝽】 true bugs 半翅目的通称，俗称放屁虫。
 
19.    【椿象】 true bugs即蝽。
 
20.    【猎蝽】 assassin bugs半翅目猎蝽科（Reduviidae）的通称。体中至大型，体壁较坚硬。头小,有细颈。喙短,3节,弓形,不能平贴在身体的腹面。捕食性为主。有的吸食哺乳类的血液,并可传播疾病。多分布暖热地区。
 
21.    【九香虫】（ Aspongopus chinensis） 又称黑兜虫、蜣螂虫。半翅目蝽科。体椭圆形，长16.5～19毫米，一般呈紫黑色，带铜色光泽，密布刻点。危害瓜类。入中药。分布长江以南地区。
 
22.    【荔枝椿】 litchi stink bug（Tessaratoma papillosa）古称石背，俗称臭屁虫。半翅目荔蝽科。体长21～28毫米，盾形，黄褐色，腹面敷白色蜡粉。荔枝和龙眼等果树的重要害虫。分布中国南方及南亚、东南亚一带。
 
23.    【田鳖】 giant water bugs半翅目负子蝽科（Belostomatidae）一些大型种类的通称。体扁阔，喙短而强。前足适宜捕捉，粗大；中、后足适于游泳，具缘毛。水生，捕食性，对鱼苗危害大。
 
24.    【大田鳖】 oriental giant water bug（Kirkaldyia deyrollei）半翅目田负子蝽科。体长65毫米。分布中国各地。渔业害虫。
 
25.    【桂花蝉】（Lethocerus indicus）半翅目负子蝽科。体长达74毫米。分布亚洲热带至大洋洲。渔业害虫。可食用。
 
26.    【负子虫】（Sphaerodema rustica）半翅目负子蝽科。体长18毫米。繁殖时雌虫将卵产于雄虫背上，雄虫负卵至若虫孵化。分布中国及印度。
 
27.    【红娘华】 water scorpions半翅目蝎蝽科（Nepidae）的通称，又称水蝎、蝎蝽。体细长，暗灰褐色。前胸长颈状。腹端有或长或短的呼吸管。水生，肉食性，能捕食幼鱼。
 
28.    【松藻虫】 back swimmers半翅目仰泳蝽科（Notonectidae）的通称。体小至中型。头与前胸紧密结合。前胸发达，后方较阔。后足甚长，浆状，停息时伸向头方。水生，背向下用后足作桨游泳。捕食性。热带较多。
 
29.    【水黾】 water striders半翅目黾蝽科（Gerridae）的通称。体形多狭长，体长1.7～36毫米，体表有拒水毛。前足为捕捉足；中、后足细长。生活于水面，靠捕捉吸食猎物体液为生。世界性分布。
 
30.    【臭虫】 bed bugs半翅目臭虫科（Cimicidae）的通称。体扁，卵圆形，红褐色。无单眼。翅退化成鳞片状。有臭腺。畏光，夜出活动，吸血。分布热带和温带。中国有2种：温带臭虫和热带臭虫。
 
31.    【盲蝽】 plant bugs半翅目盲蝽科（Miridae）的通称。小至中型。身体质地较脆弱。无单眼。触角4节。喙4节。臭腺开口大。半翅目最大的1科。多为植食性。世界性分布。
 
32.    【棉盲蝽】 cotton mirids半翅目盲蝽科为害棉花作物的种类。主要有绿盲蝽、三点盲蝽、苜蓿盲蝽、及中黑盲蝽。
 
33.    【啮虫目】 Psocoptera通称啮虫。小型柔软昆虫。体长1.5～5毫米。头大，活动自如。复眼突出，左右远离。口朝下，口器适宜咀嚼。有翅或无翅。杂食性。一些种类如书虱和窃虫为家庭和仓储害虫。遍布世界。
 
34.    【啮虫】 psocids啮虫目的通称。
 
35.    【书虱】 cereal psocid（Liposcelis divinatorius）啮虫目书啮科。体小而扁。后足短，不超过腹部末端。触角短，有分节。复眼退化。有翅或无翅。生活于室内，危害书籍、谷物、木材及衣物。
 
36.    【窃虫】 book louse（Atropos pulsatorium）啮虫目窃虫科。体长1.5～2.0毫米，体色暗。一般翅全缺，或至多仅存鳞片状前翅。啮食动物标本及纸张。分布世界。
 
37.    【食毛目】 Mallophaga通称鸟虱、羽虱。小型寄生性昆虫。体扁平。口朝前或朝下，口器适宜咀嚼。足短，具1～2爪，适宜攀缘。无翅。常寄生在鸟或哺乳类的皮肤及毛发上。世界性分布，常见有鸡虱﹑鸭虱等。
 
38.    【鸟虱】 bird lice 食毛目的通称。
 
39.    【羽虱】 bird lice 食毛目的通称。
 
40.    【虱目】 Anoplura通称虱、虱子。小型寄生性昆虫。体扁平。头小而尖。口朝前，口器适宜刺吸，喙不分节。足粗短，有爪，适宜攀缘。胸部各节愈合，无翅。寄生于哺乳动物和人体上。世界性分布。
 
41.    【虱】 true lice 虱目的通称。
 
42.    【头虱】 head louse俗称虮。 （Pediculus humanus capitis）虱目虱科。体较小而黑褐，触角较粗。腹部分节较显明。寄生于人头部，产卵于头发上，呈灰白色，粒粒显著，
43.     
44.    【体虱】（Pediculus humanus corporis）又称衣虱。虱目虱科。身体较大，色泽淡白，触角细。腹部分节较模糊。常栖于衣隙缝尖，吸血时始移近皮肤。吸血并可传播斑疹伤寒、回归热和鼠疫等疾病。
 
45.    【缨翅目】 Thysanoptera通称蓟马。小型细弱昆虫。口朝下，口器适宜锉吸。足短小，末端有一可伸缩的泡状中垫，适宜附着。翅膜质狭长，边缘有长而整齐的缨毛。多为植食性。有些种类是重要的农业害虫。世界性分布。
 
46.    【蓟马】 thrips缨翅目的通称。有些种类是重要的农业害虫，如稻蓟马（Thrips oryzae）为害水稻；烟蓟马（T. tabaci）为害烟草、棉花等，并可传播植物疾病。
 
47.    【鞘翅目】 Coleoptera通称甲虫。小至大型昆虫。体躯坚硬。口器适宜咀嚼。前胸发达。前翅角质，称鞘翅；后翅膜质，折叠在鞘翅下，或缺。食性复杂。陆生或水生。种类极多，为动物界最大的一目。世界性分布。
 
48.    【甲虫】 beetles鞘翅目的通称。
 
49.    【虎甲】 tiger beetles鞘翅目虎甲科（Cicindelidae）的通称。体中型，具鲜艳的色斑和金属光泽。头比胸部略宽，口朝下。上颚发达，弯曲有齿。成虫行动迅速，常静伏地面或低飞捕食小虫，当人走近时，常向前作短距离飞翔。
 
50.    【骆驼虫】 tiger beetles鞘翅目虎甲科幼虫的俗称。虎甲幼虫常于路面钻小圆洞，深居洞内，捕食时移近洞口，张开上颚，等待小动物投奔颚间，牵入洞内。身体背面有倒钩一对，以固定位置，免被拉出洞外。
 
51.    【步行虫】 ground beetles 又称步甲。鞘翅目步行虫科（Carabidae）的通称。体长小至大型，体黑色或褐色而有光泽。头小于胸部，口朝前。大多无飞翔能力，爬行敏捷。多为肉食性。
 
52.    【龙虱】 predaceous diving beetles鞘翅目龙虱科（Dytiscidae）的通称。体小到大型，流线型，背腹间隆拱。后足侧扁，被长毛，适于游泳。水生，肉食性，捕食鱼苗或其他小虫。可食用和药用。
 
53.    【豉甲】 whirligig beetles又称豉甲。鞘翅目豉甲科（Gyrinidae）的通称。体小至中型，背面隆起而光滑，豆豉状，黑色有光泽。中、后足短阔，扁平桨状。常聚集水面，迴旋运动，捕食昆虫。
 
54.    【牙甲】 water scavenger beetles鞘翅目水龟虫科（Hydrophilidae）的通称。体小至大型。长卵形，与龙虱相似，背面极隆起，色暗。一般水生，幼虫捕食鱼苗等小动物，有些危害秧苗或麦苗。
 
55.    【郭公虫】 checkered beetles 鞘翅目郭公虫科（Cleridae）的通称。体长5～12毫米。足细长，前足基节突出于体外。幼虫长形，体披厚毛。捕食性。主要分布热带和亚热带。
 
56.    【隐翅虫】 rove beetles 鞘翅目隐翅虫科（Staphylinidae）的通称。体小型。鞘翅短，末端平截，覆盖腹部前端。腹部末端细尖。一般取食腐败物质，亦有捕食性种类。广布世界各地。
 
57.    【埋葬虫】 carrion beetles又称葬甲。鞘翅目埋葬虫科（Silphidae）的通称。体长1.5～30毫米。许多种类食动物尸体，常群集于鸟兽尸体旁掘穴，使其陷入土中而取食。多分布北半球。
 
58.    【金龟子】 scarabs通称蛴螬。鞘翅目金龟子科（Scarabaeidae）的通称。体多为卵圆形,体表坚硬平滑而有光泽，覆有鳞片和绒毛。触角鳃叶状。足为开掘足。幼虫体常弯曲呈马蹄形，背上多横皱纹，居于土中，重要地下害虫。
 
59.    【蛴螬】 grubs金龟子科幼虫的通称。
 
60.    【蜣螂】 dung beetles鞘翅目金龟子科金龟子亚科（Scarabaeinae）的俗称，又称屎克螂。体宽卵圆形，体长2～23毫米，几乎全为黑色。幼虫一般生活于动物粪便中，成虫取粪作球，然后埋藏于地下供食用。
 
61.    【屎克螂】 dung beetles即蜣螂。
 
62.    【独角仙】 rhinoceros beetle又称双叉犀金龟。（Allomyrina dichotoma）。鞘翅目犀金龟科。体长35～60毫米，黑褐色。雄虫的头上有角状突起，背面比较光亮；雌虫略小，无角突，背面较粗暗。植食性。分布中国、日本、朝鲜和南亚一带。
 
63.    【锹甲】 stag beetles鞘翅目锹甲科（Lucanidae）的通称。又称鹿角虫。雄虫上颚大而突出呈鹿角状。鞘翅覆盖整个腹背，呈圆锹形。幼虫以朽木为食，多发生于森林地带。热带种类居多。
 
64.    【瓢虫】 ladybirds鞘翅目瓢虫科（Coccinellidae）的通称，俗称花大姐、看麦娘。体呈半球形，腹面平坦，色多美丽，具斑纹。头小，一部分常隐藏在前胸背板之下。有植食性和捕食性两类。世界性分布。
 
65.    【七星瓢虫】 seven spot ladybird （Coccinella septempunctata）鞘翅目瓢虫科。体卵圆形，背面作半球形拱起，长5～7毫米。头部黑色。鞘翅红色或橙黄色，上有7个黑点。肉食性，捕食棉蚜、豆蚜，为著名的农业益虫。
 
66.    【马铃薯瓢虫】 potato lady beetle （Henosepilachna vigintioctomaculata）鞘翅目瓢虫科。体长6～8毫米，背面红棕至黄红色。头背面有两个有时连合的黑斑。鞘翅各有14个黑斑。蔬菜害虫，危害马铃薯、茄子、番茄等。
 
67.    【萤火虫】 fireflies鞘翅目萤科（Lampyridae）的通称。体小至中型，细长扁形，较软。腹部末端下方有特殊的发光器。夜晚活动，能发光。捕食性。一般生活于多湿温暖地区。
 
68.    【吉丁虫】 flat-headed borers 鞘翅目吉丁虫科（Buprestidae）的通称。体小至大型，窄长而扁，腹部趋尖，多鲜艳，有金属光泽。头小，嵌入前胸。前胸大，与其后的中胸密结，不能活动。幼虫钻蛀树木为害。
 
69.    【叩头虫】 click beetles鞘翅目叩甲科（Elateridae）的通称，又称叩甲、金针虫。体小至大型，色暗。前胸背板后角尖锐，腹板后部突出呈楔形。仰卧时能借前胸的弹动而跃起。幼虫细长而坚实。
 
70.    【金针虫】 wireworms叩头虫幼虫的通称。生活于地下，危害植物种子、根及幼苗等，是农作物重要地下害虫。
 
71.    【皮蠹】 skin beetles 鞘翅目皮蠹科（Dermestidae）。体小至中型，长卵形或卵圆形，色暗。头较小。触角短棍棒状，常藏于前胸腹面的沟内。喜食动物干制品、皮革和标本等。有些是重要的检疫对象。
 
72.    【谷蠹】 lesser grain borer（Rhyzopertha dominica）又称米长蠹。鞘翅目长蠹科。体长2.5～3.0毫米，暗褐色，有光泽。头部隐藏于前胸背板下面，与胸部垂直。幼虫体型弯曲，披淡黄色微毛。重要的仓储粮食害虫。
 
73.    【芫菁】 blister beetles鞘翅目芫菁科（Meloidae）的通称，俗称地胆、斑蝥等。体中型，长圆筒形。鞘翅较柔软。幼虫寄生于蜂巢内，或食蝗虫卵。成虫食害豆科植物及杂草，遇惊时常从腿关节处分泌黄色液体，含药用成分斑蝥素。
 
74.    【地胆】 Meloe 鞘翅目芫菁科地胆属Meloe的通称。常见的有圆胸地胆，产于中国东北及俄罗斯、朝鲜和日本。
 
75.    【斑蝥】鞘翅目芫菁科斑蝥属Mylabris的通称。分布大洋洲外的世界各地。中药常用的有小斑蝥和大斑蝥。
 
76.    【豆象】 bean weevils鞘翅目豆象科（Bruchidae）的通称。体小，卵圆形。额延长成短喙状。鞘翅短，腹末露出。幼虫蛀种子，危害豆科植物。成虫有访花习性。
 
77.    ［蚕豆象］ broad bean weevil（Laria rufimanus）鞘翅目豆象科。体长4.5～5.5毫米，深灰褐色。幼虫体肥厚，乳白色。主要危害蚕豆。广布世界各地。
 
78.    【豌豆象】 pea weevil（Laria pisorum）鞘翅目豆象科。成虫体长4～5毫米，黑色，密生灰白色细毛。幼虫体肥厚，多皱折，黄白色。主要危害豌豆。广布世界各地。
 
79.    【绿豆象】 Chinese bean weevil（Callobruchus chinensis）又称小豆象。鞘翅目豆象科。成虫体长2.5～3.5毫米，茶褐或赤褐色。幼虫肥大弯曲，多横皱纹，乳白色。危害绿豆等豆科作物。广布世界各地。
 
80.    【叶甲】 leaf beetles鞘翅目叶甲科（Chrysomelidae）的通称，又称金花虫。体小至中型，通常为椭圆形，背面隆起。体色多样，多有金属光泽。植食性，食叶。有不少种类是重要的农林业害虫。世界性分布。
 
81.    【金花虫】 leaf beetles即叶甲。
 
82.    【铁甲虫】 army weevil又称稻铁甲（Dicladispa armigera）。鞘翅目叶甲科铁甲亚科。体长约5毫米，黑色有金属光泽。前胸背板及鞘翅上有刻点和棘刺。水稻害虫。幼虫潜食叶肉，形成长囊状薄膜；成虫啮食叶片，形成条状白沟。
 
83.    【龟甲】 tortoise beetles 鞘翅目叶甲科龟甲亚科（Cassidinae）的通称。体小至中型，圆形或椭圆形，隆背平腹，前胸背板及鞘翅外缘外延呈薄片状，头隐于前胸背板下，似龟。色彩艳丽，有金属光泽。植食性。主产热带和亚热带。
 
84.    【黄守瓜】 cucumber beetle（Aulacophora femoralis）俗称瓜萤。鞘翅目叶甲科萤叶甲亚科。体长约6～9毫米，近椭圆形，橙色或橙红色。瓜类重要害虫。成虫啮食瓜苗叶片，形成圆形缺孔。幼虫在土中食害细根或蛀茎。分布东亚一带。
 
85.    【跳甲】 flea beetles鞘翅目叶甲科跳甲亚科（Alticinae）的通称。体小型，长椭圆形。后足腿节膨大，善于跳跃。植食性。其中菜跳甲属一些种类为重要的蔬菜害虫。世界性分布。
 
86.    【马铃薯甲虫】 Colorado beetle（Leptinotarsa decemlineata） 鞘翅目叶甲科。体长约10毫米，红橙或黄色。每一鞘翅具5条黑色纵纹。成虫和幼虫都危害马铃薯的叶片和嫩尖。原产美国落基山区，现欧洲多国发生。
 
87.    【大猿叶甲】 cruciferous leaf beetle（Colaphellus bowringi）鞘翅目叶甲科。体长4～5毫米，蓝黑色而有光泽，背面密布不规则的大刻点。十字花科蔬菜害虫，食叶成孔，严重时仅剩叶脉。分布中国和东南亚地区。
 
88.    【小猿叶甲】 daikon leaf beetle（Phaedon brassicae）鞘翅目叶甲科。体长3毫米，蓝黑色，有金属光泽。蔬菜害虫，取食叶片呈缺刻或孔洞，严重时，食成网状，仅留叶脉。产于中国及日本、朝鲜、印度和越南。
 
89.    【天牛】 long-horned beetles 鞘翅目天牛科（Cerambycidae）的通称。体长圆筒状。触角着生在额的突起上，超过体长。幼虫蛀食树木枝干和树根，为果树和林木重要害虫。种类甚多，遍布世界各地。
 
90.    【桑天牛】 mulberry borer （Apriona germari）鞘翅目天牛科。体长26～51毫米，黑色，密被黄褐色短毛。鞘翅基部密布黑色小颗瘤，肩角有一尖刺。幼虫乳白色。桑树、果树和林木害虫。分布中国及日本、朝鲜和印度。
 
91.    【象鼻虫】 weevils鞘翅目象鼻虫科（Curculionidae），又称象甲。体微小至大型，体壁坚硬。头部向前延伸呈象鼻状，末端着生口器。幼虫无足，蛆状。植食性。许多种类为重要害虫。分布遍及世界。
 
92.    【谷象】 granary weevil（Sitophilus granarius）鞘翅目象鼻虫科。体长3～4 毫米，赤褐色有金属光泽。前胸背板上有椭圆形刻点。后翅退化。幼虫白色，足退化，多皱纹。贮藏谷物的主要害虫。分布于气候较冷地区，中国仅分布新疆和甘肃。
 
93.    【米象】 rice weevil（Sitophilus oryzae）鞘翅目象鼻虫科。体长2.3～3.5毫米，深赤褐色。每一鞘翅上有二个赤褐色斑纹。后翅发达。幼虫乳白色，足退化，体肥厚。贮藏谷物的主要害虫。温暖地区发生较盛。
 
94.    【竹象】 bamboo weevil（Cyrtotrachelus longimanus）鞘翅目象鼻虫科。体长约21～33毫米，赤褐色。鞘翅各有9条纵纹。幼虫乳白色，纺锤形。幼虫蛀食竹笋，为竹类主要害虫。产于中国和日本。
 
95.    【梨虎】（Rhynchites foreipennis） 鞘翅目象鼻虫科（Curculionidae）。体长7～10毫米，有紫铜色光泽，触角、足和腹面蓝紫色，全身密被灰绒毛。梨、桃、苹果和枇杷等果树的重要害虫。分布中国和朝鲜。
 
96.    【稻象】 paddy weevil又称稻象甲（Echinocnemus squameus），稻象鼻虫。鞘翅目象鼻虫科。体长约5毫米，暗灰褐色或灰黑色，被有灰黄色毛。每鞘翅有纵沟10列，近端处有一小白斑。幼虫危害稻根，成虫蛀食稻秧茎叶。稻区均有分布。
 
97.    【松大象甲】（Sipalus hypocrita）鞘翅目象鼻虫科。成虫体长15～25毫米，灰黑色，翅上有黑白交错的长方形斑。幼虫乳白色，体末有4个突起。松树害虫，幼虫和成虫蛀食树干和树皮。
 
98.    【卷叶象甲】 leaf-rolling weevils鞘翅目卷象科（Attelabidae）的通称。体中小型，无鳞片，一般体色鲜艳，具金属光泽。头基部延长成颈状。雌虫将新产卵卷于叶内。分布中国、日本、朝鲜和俄罗斯。
 
99.    【小蠹】 bark beetles鞘翅目小蠹科（Scolytidae）的通称。体小型，圆筒状，多为褐色。头部为前胸背板掩盖。触角较短，端部3或4节膨大成锤状。成虫和幼虫蛀食树皮和木质部，为森林重要害虫。
 
100.【捻翅目】 Strepsiptera通称捻翅虫。小型寄生性昆虫。雄虫有分支的触角，有棒状的前翅和膜质扇状的后翅，有足，营自由生活。绝大多数雌虫触角、翅和足均退化，状如蛆，终生寄生在其他昆虫体内。世界性分布。
 
101.【捻翅虫】 strepsipterans捻翅目的通称。
 
102.【广翅目】 Megaloptera中至大型昆虫，包括泥蛉和鱼蛉。口朝前，口器适宜咀嚼。前胸方形。翅大，膜质，有网状翅脉，停息时呈屋脊状或平置于腹部背面。幼虫水生。广布世界各地。
 
103.【鱼蛉】 dobsonflies广翅目鱼蛉科（Corydalidae）的通称，又称齿蛉。体长超过25毫米。雄虫上颚强大。幼虫生活于流水中，捕食其他水生昆虫和小型无脊椎动物。成虫多栖息在树干上，夜晚有趋光性。
 
104.【泥蛉】 alderflies 广翅目泥蛉科（Sialidae）的通称。体中型。无单眼。触角长，丝状。幼虫生活于静水中，捕食水底小虫。成虫栖息于岸边植物上。
 
105.【脉翅目】 Neuroptera通称蛉。小至大型昆虫。包括草蛉、褐蛉和蚁蛉。体细长柔弱。口朝下，口器适宜咀嚼。前、后翅相似，膜质，翅脉网状。捕食性。可作为天敌用于防治害虫。世界性分布。
 
106.【蛉】 lacewings脉翅目的通称。
 
107.【草蛉】 green lacewings蚜狮。脉翅目草蛉科（Chrysopidae）的通称。体细长，长约10毫米，多绿色。触角长丝状。复眼有金色闪光。常在树叶上产卵。卵黄色，有长柄。幼虫纺锤状，捕食蚜虫等软体昆虫并吸食其体液。
 
108.【褐蛉】 brown lacewings 脉翅目褐蛉科（Hemerobiidae）的通称。体小至中型，褐色，并常有金属光泽。触角长，念珠状。成虫和幼虫都捕食蚜虫、介壳虫等，对园林果木有益。
 
109.【蚁蛉】 antlions又称蚁狮。脉翅目蚁蛉科（Myrmeleontodae）的通称。体细长，长25～35毫米。触角棒状。翅狭长。幼虫在树荫或檐下砂地中造漏斗状陷井，潜伏井底，捕食误落井底的蚂蚁。
 
110.【粉蛉】 dustywings 脉翅目粉蛉科（Coniopterygidae）的通称。体小型，体和翅被有蜡质白粉。触角长丝状。翅脉简单。幼虫捕食蚜、蚧和螨等。
 
111.【蝶角蛉】 owlflies 脉翅目蝶角蛉科（Ascalaphidae）的通称。体大型，外形酷似蜻蜓类，但体表布满细毛。触角长丝状，末端膨大呈棍棒状或头状。成虫和幼虫都捕食小虫。
 
112.【蛇岭目】 Raphidiodea通称蛇岭。小至中型昆虫。体长而软。口朝下，口器适宜咀嚼。前胸细长如颈。前、后翅相似，膜质，翅脉网状。雌虫有可伸缩的产卵器。幼虫生活在树皮下。肉食性。主要分布北半球。
 
113.【蛇岭】 snakeflies蛇岭目的通称。
 
114.【长翅目】 Mecoptera通称蝎蛉。小至中型昆虫。体细长。头部向下延伸成喙状，口器适宜咀嚼。足细长。前、后翅相似，膜质；或无翅。雄性腹部末端外生殖器膨大成球状，上弯呈蝎尾状。捕食性。分布于世界温暖地区。
 
115.【蝎蛉】 scorpion flies长翅目的通称。
 
116.【毛翅目】 Trichoptera俗称石蚕。小至中型昆虫，通称石蛾。成虫外形似小蛾类。触角长丝状。口器适宜咀嚼，但较退化。翅膜质，被有粗细不等的毛或鳞，停息时翅迭置呈屋脊状。幼虫水生，有的可危害水稻苗根。世界性分布。
 
117.【石蛾】 caddisflies 毛翅目的通称。
 
118.【鳞翅目】 Lepidoptera俗称 蛾、蝶。小至大型昆虫。体和翅上密被鳞片。复眼大。口器具可卷曲的喙，适宜吮吸。幼虫多足，蠋型，多为植食性。成虫有吸食花蜜的习性。遍布全世界，以热带种类为多。
 
119.【蛾】 moths 即鳞翅目蛾类。体微小至大型，依体型大小分为小蛾类和大蛾类。触角多形，有鞭状、丝状、羽状、栉齿状及锤状等。翅色彩大多暗淡，停息时呈屋脊状置放。成虫夜间活动为主，常有趋光性。
 
120.【蝶】 butterflies 即鳞翅目蝶类，又称蝴蝶。体型小至大型。触角锤状或棍棒状。翅色彩大多鲜艳，停息时竖立于背上。成虫白天活动，吸食花蜜，夜间不趋光。具收藏价值，有些种类极为珍稀。
 
121.【螟蛉】 bollworms  鳞翅目各种蛾类的幼虫，尤指包括麦蛾科的红铃虫（Platyedra gossypiella）及夜蛾科棉铃虫（Heliothis armigera）在内的一些危害农作物的种类。成语“螟蛉有子，蜾蠃负之”记述的是其被蜾蠃蜂寄生的现象。
 
122.【蝙蝠蛾】 swift moths 鳞翅目蝙蝠蛾科（Hepialidae）的通称。体多中型，粗壮，多毛。头小。触角短，丝状。口器退化。常在傍晚近地飞行，速度很快，犹如蝙蝠。幼虫钻茎蛀木。
 
123.【冬虫夏草蛾】 Hepialus armoricanus 鳞翅目蝙蝠蛾科（Hepialidae）。幼虫栖地下，食植物根须，多分布青藏高原及边缘地区。受冬虫夏草菌（Cordyceps sinensis）寄生后，夏季由僵死幼虫的头颈部发出细长棒状的菌体，称冬虫夏草，可药用。
 
124.【谷蛾】1 clothes moths 鳞翅目谷蛾科（Tineidae）的通称。体小，翅展20毫米以下。头和触角通常被粗糙毛状鳞片。触角不长过翅长。后足胫节被长毛。幼虫食害干的动、植物质和菌类。
 
2 European grain moth Tinea granella。鳞翅目谷蛾科的一种。世界共有种，幼虫是仓储谷物的重要害虫。
 
125.【衣蛾】 common clothes moth又称幕谷蛾（Tineola bisselliela）。鳞翅目谷蛾科。体长4～8毫米,淡棕色。成虫于光线微弱时在室内飞翔。幼虫危害毛皮衣物或标本。遍布世界。
 
126.【潜叶蛾】 leaf-mining moths泛指鳞翅目幼虫潜叶危害的部分小蛾类，包括微蛾科（Nepticulidae）、潜蛾科（Lyonetiidae）和细蛾科（Gracillariidae）等。
 
127.【羽蛾】 plume moths鳞翅目羽蛾科（Pterophoridae）的通称。体小型，细长。翅纵裂。前翅一般2裂，后翅3裂，形像鸟羽。幼虫早期潜叶，后期卷叶或蛀茎。成虫白天飞行。
 
128.【菜蛾】 diamond-back moths又称小菜蛾（Plutella xylostella）。鳞翅目菜蛾科。翅展12～15毫米。前翅灰黑色或灰白色，有淡黄色波纹；后翅银灰色。危害十字花科蔬菜及其他野生植物。遍布世界。
 
129.【棉红铃虫】 pink bollworm（Platyedra gossypiella）又称红铃虫。鳞翅目麦蛾科。体长约6.5毫米，灰白色。前翅尖叶形，翅面有不规则的黑褐色横纹4条。棉花的主要害虫。幼虫粉红色，钻入棉蕾、花、青铃为害，引起落蕾落花和僵瓣烂铃。
 
130.【红铃虫】 pink bollworm 即棉红铃虫。
 
131.【苹果巢蛾】 apple hyponomeut（Yponomeuta padella）俗称苹果巢虫。鳞翅目巢蛾科。体长约10毫米，全身有丝质银色光泽。前翅狭长，白色，翅面散布多个黑斑。幼虫黑褐色，有黑色短毛。危害苹果、梨、沙果等果树。
 
132.【黄刺蛾】 oriental moth（Cnidocampa flavescens）俗称洋辣子。鳞翅目刺蛾科。翅展29～36毫米。体大部黄色。老熟幼虫蛞蝓型，黄绿色，背面有一大型紫褐斑，两侧生丛刺。茧壳坚硬，状如雀卵，胶着于树枝或树干上。危害多种果树和林木。
 
133.【洋辣子】 oriental moth即黄刺蛾。
 
134.【卷蛾】 leaf-roller moths鳞翅目卷蛾科（Tortricidae）的通称。体小型，较粗壮，多为褐色或棕色。前翅近长方形。幼虫常卷叶或蛀茎、花托或果实，为果树及森林害虫。世界性分布。
 
135.【大豆食心虫】 soybean pod borer（Leguminivora glycinivorella）又称豆荚蠹。鳞翅目卷蛾科。体长5～6毫米，黄褐色至暗褐色。前翅前缘有约10组黄白色钩状纹。幼虫淡黄或橘黄色，入豆粒为害。大豆主要害虫。
 
136.【苹果蠹蛾】 codling moth 又称苹果小卷蛾（Laspeyresia pomonella）。鳞翅目卷蛾科。体灰褐色带紫色光泽。头部具发达的灰白色鳞片丛。前翅有3条青铜色条纹，其间夹杂4～5条褐色横纹。幼虫危害苹果、桃、杏等果树。中国仅西北地区有分布。
 
137.【食心虫】 fruit moths蛀食桃、梨、苹果、花红、李和梅等果实的鳞翅目幼虫的通称。主要有蛀果蛾科的桃小食心虫和卷蛾科的梨小食心虫等。
 
138.【梨小食心虫】 oriental peach moth（Grapholitha molesta）俗称梨小、桃折心虫。鳞翅目卷蛾科。翅展10～15毫米。体灰褐色。著名果树害虫。一般幼虫在早春食害桃树嫩梢，形成枯心，以后转食梨果。
 
139.【桃小食心虫】 peach fruit moth（Carposina niponensis）鳞翅目蛀果蛾科。翅展13～18毫米。体淡灰褐色。前翅灰白色，有一近三角形蓝黑斑。幼虫蛀果危害桃、苹果、山楂、枣等果树。
 
140.【螟蛾】 pyralid moths鳞翅目螟蛾科（Pyralidae）的通称。体小至中型。前翅狭三角形；后翅较宽，扇形。幼虫体细长，光滑，毛稀少。蛹多裸露。许多种类是农林业重要害虫。
 
141.【三化螟】 yellow rice borer（Scirpophaga incertulas）鳞翅目螟蛾科。翅展21～25毫米。雌蛾浅黄褐色，前翅黄色，中部有一黑斑。雄蛾灰白，前翅灰黄褐色，中部有1个、外缘有7个黑斑。幼虫蛀食稻茎和稻穗。分布亚热带至温带南部。
 
142.【二化螟】 Asiatic rice borer（Chilo supressalis）鳞翅目螟蛾科。翅展20～28毫米。前翅黄褐色，沿外缘有6～7个小黑斑；后翅灰白。危害水稻等禾本科作物。黑龙江至海南均有分布。
 
143.【钻心虫】 sugarcane stem borers又称甘蔗螟虫。甘蔗害虫。小蛾类。主要有卷蛾科的甘蔗黄螟（Argyroploce  schistaceana）、螟蛾科的甘蔗二点螟（Chilo infuscatellus）和白螟（Scirpophaga nivella）。幼虫蛀入蔗苗和蔗茎，造成枯心苗。蔗区均有分布。
 
144.【粟灰螟】 sugarcane stem borer 又称甘蔗二点螟（Chilo infuscatellus）鳞翅目螟蛾科。翅展18～25毫米。雄蛾暗灰褐色，胸部背面暗黄，腹部背面白色。雌蛾灰黄。幼虫蛀食甘蔗，在北方危害粟、黍、玉米等。粟的主要害虫。多分布蔗区。
 
145.【高粱条螟】 spotted sugar borer（Chilo sacchariphagus）鳞翅目螟蛾科。体长12～14毫米。头胸背面灰黄色，腹面黄白。前翅外缘有近20条暗褐色细线纵列，中部有一小黑斑。高粱和甘蔗害虫。主要分布中国及东南亚和埃及。
 
146.【豆荚螟】 limabean pod borer（Etiella  zinckenella）鳞翅目螟蛾科。体长10～11毫米，灰褐色。前翅狭长，紫灰色，混有黄褐色鳞片，前缘有一条白色纵带；后翅灰白色。幼虫食害大豆、绿豆、菜豆、扁豆和豆科绿肥作物等。
 
147.【桃蛀螟】 yellow peach moth （Conogethes punctiferalis）鳞翅目螟蛾科。体长约12毫米，橙黄色。前翅上散布20余个黑点，后翅有10多个黑点。腹部有成排黑斑。幼虫蛀害桃、李、柑橘、梨、石榴等多种果树和向日葵、玉米。
 
148.【草地螟】 beet webworm（Loxostege sticticalis）又称甜菜网螟、黄绿条螟。鳞翅目螟蛾科。体长10～12毫米，暗褐色。颜面突起呈圆锥状。幼虫为害甜菜等多种农作物。分布北纬34°～54°的森林及草原地带。
 
149.【松梢螟】 larger pine shoot borer（Dioryctria rubella）鳞翅目螟蛾科。翅展约22毫米，灰褐色。前翅暗褐色，有3条灰白波纹状横带，中央有一白点；后翅灰白色。幼虫蛀食嫩梢和球果，危害云杉、马尾松等。
 
150.【桑螟】 mulberry pyralid学名Diaphania pyloalis。鳞翅目螟蛾科。体长10毫米，白色有绢丝光泽。胸背中央暗褐色。前翅外缘、中央及翅基有棕褐色带；后翅外缘暗褐色。幼虫危害桑树，卷叶并食叶肉。
 
151.【灯蛾】 tiger moths 鳞翅目灯蛾科（Arctiidae）的通称。体小至中型，少数大型，体厚多毛，体色多鲜艳有斑纹。如遇干扰，能分泌黄色腐蚀性刺鼻的臭油汁，有些种类能发出爆裂声以驱避敌害。多分布热带和亚热带。
 
152.【茶蓑蛾】 tea bagworm（Cryptothelea minuscula）又称茶避债虫。鳞翅目蓑蛾科。雌蛾无翅，蛆状，长约26毫米，白色。雄蛾有翅，足发达，体长约17毫米，暗褐色。幼虫暗褐色，用丝和枝叶结成蓑囊，栖息其中。茶树等果木害虫。
 
153.【斑蛾】 forester moths 鳞翅目斑蛾科（Zygaenidae）的通称。体大小和形状多样，有小蛾形、天蛾形、蝶形等。成虫白天活动，飞翔力弱。幼虫身上有疣，有的卷叶为生，有的营自由生活。广布北半球。
 
154.【梨星毛虫】 pear leaf worm又称梨叶斑蛾（Illiberis pruni），俗称饺子虫、梨包虫。鳞翅目斑蛾科。翅展约24毫米。体及翅暗青蓝色有光泽。翅半透明，有细毛。幼虫淡黄色，危害梨、苹果等多种果树。分布中国、朝鲜和日本。
 
155.【枯叶蛾】 tent caterpillar moths俗称毛虫。鳞翅目枯叶蛾科（Lasiocampidae）的通称。体中至大型，粗壮，有厚毛，停息时形似枯叶。雌蛾笨拙，雄蛾活泼，有强的飞翔能力。幼虫大而多毛。分布广，尤以热带为多。
 
156.【松毛虫】 pine caterpillars鳞翅目枯叶蛾科松毛虫属（Dendrolimus）的通称。森林主要害虫类群。包括马尾松毛虫（D. punctatus）、落叶松毛虫（D. superabs）、油松毛虫等。
 
157.【天幕毛虫】 tent caterpillar（Malacosoma neustria testacea）鳞翅目枯叶蛾科。翅展24～40毫米。体黄褐色。幼虫群集潜伏于网巢内，呈天幕状，夜出食叶并常将树叶食尽。多数阔叶树主要害虫。
 
158.【毒蛾】 tussock moths 鳞翅目毒蛾科（Lymantriidae）的通称。体中到大型，粗壮多毛，大小和体色雌雄各异。口器退化。幼虫被毒毛，在瘤上形成毛束或毛刷，有群居和吐丝下垂的习性。多为植食性，危害多种农作物及果木。
 
159.【茶毛虫】 tea tussock moth又称茶毒蛾（Euproctis pseudoconspersa）。鳞翅目毒蛾科。体长9～12毫米。雌蛾粉黄或黄褐色，尾端有一层橙黄色绒毛；雄蛾棕褐色，稀布黑鳞。幼虫黄褐色，危害茶、柑橘、梨、玉米等果树和作物。分布中国南方及日本。
 
160.【桑毛虫】 mulberry tussock moth又称黄尾毒蛾（Porthesia similis），俗称金毛虫。鳞翅目毒蛾科。雌蛾体长18毫米，雄蛾12毫米。体和翅白色，前翅后缘有2个黑斑。幼虫头部黑褐色，胸腹部黄色，食叶芽及嫩叶，危害桑树等多种树木。
 
161.【舞毒蛾】 gypsy moth（Lymantria dispar）俗称柿毛虫。鳞翅目毒蛾科。雌蛾翅展55～75毫米，黄白色，有黑棕色斑纹；雄蛾翅展40～50毫米，棕色，有黑褐色斑纹。幼虫淡褐色，食量大，是世界性果树和林木重要害虫。
 
162.【夜蛾】 owlet moths 鳞翅目夜蛾科（Noctuidae） 的通称。又称夜盗虫、切根虫。体中至大型，粗壮，一般暗灰褐色。前翅常有深色条纹或肾状纹。幼虫一般夜间取食，危害农作物，大量发生时，有成群迁移习性。
 
163.【甘蓝夜蛾】 cabbage army moth（Mamestra brassicae）鳞翅目夜蛾科。体长18～25毫米，灰褐色，胸背有暗色毛簇。前翅褐色，有黑白斑纹；后翅淡褐色。幼虫绿色或褐色，危害十字花科蔬菜、甜莱、棉花、麻类、禾谷类等多种作物。农业重要害虫。
 
164.【大螟】 purplish stem borer （Sesamia inferens）鳞翅目夜蛾科。体长13～15毫米。头和胸部淡褐黄色，腹部淡黄色。前翅淡黄褐色，散布黑色斑点；后翅白色。幼虫肉白色，背面粉红色，危害茎杆，是禾本科作物的重要害虫。主产亚洲稻区。
 
165.【地老虎】 cutworms鳞翅目夜蛾科切根虫亚科（Agrotinae）幼虫的俗称，又称地蚕、切根虫。重要地下害虫，主要种类有小地老虎（Agrotis ypsilon）、大地老虎（A. tokionis）和黄地老虎（A. segetis）等。危害烟草、棉花、蔬菜等多种作物。
 
166.【棉铃虫】 cotton bollworm（Heliothis armigera）鳞翅目夜娥科。体长14～18毫米，灰褐色。前翅淡红褐色或淡青灰色，有暗褐斑纹；后翅灰白。幼虫体色多样，棕色到绿色，危害茄类、禾谷类等多种作物。棉花重要害虫，棉区均有分布。
 
167.【烟草夜蛾】 oriental tobacco budworm俗称烟青虫。（Helicoverpa assulta）鳞翅目夜蛾科。体长15～18毫米，头、胸部及前翅黄褐色，腹部和后翅淡褐黄色。幼虫头部淡黄色，体黄绿或青灰色。危害烟草、茄类及棉花等。分布亚洲及非洲。
 
168.【棉金刚钻】 cotton spiny worms鳞翅目夜蛾科钻夜蛾属（Earias）危害棉花种类的通称，又称棉钻心虫。主要种类有鼎点金刚钻、翠纹金刚钻和埃及金刚钻。幼虫侵入嫩梢、果枝、蕾铃等为害。
 
169.【小造桥虫】 cotton leaf caterpillar（Anomis flava）鳞翅目夜蛾科。体长10～12毫米。头和胸部黄色，腹部灰黄色。雄蛾前翅黄褐色，后翅淡黄色。雌蛾色淡。幼虫绿色，危害棉花、烟草等。
 
170.【杨天社蛾】 poplar prominent又称杨扇舟蛾（Clostera anachoreta）。鳞翅目舟蛾科。体长约18毫米，灰褐色。前翅有3条灰白色横纹。幼虫黑褐色，密披黄色长毛，食叶为害。杨树主要害虫。
 
171.【栎褐天社蛾】（Phalerodonta albibasis） 鳞翅目舟蛾科。翅展37～48毫米。体灰褐色，前翅基部和前缘黑褐色，前翅内外各有一条斜走锯齿纹。幼虫头红体绿，有紫褐色斑纹，食叶为害。栎树主要害虫。
 
172.【天蛾】 sphinx moths鳞翅目天蛾科（Sphingdae）的通称。体粗大呈梭形。触角未端缩小成钩。前翅狭长，顶角尖锐；后翅较小。喙发达。多夜间活动，飞翔力强。幼虫肥大，圆柱形，光滑，受惊时常收缩昂起前驱。许多种类为森林和作物害虫。
 
173.【豆天蛾】 bean hawk moth（Clanis bilineata）鳞翅目天蛾科。体长40～45毫米。体及翅黄褐色，头及胸部背面有暗褐色斑纹。前翅前缘中央有半圆形褐绿色斑；后翅暗褐色。幼虫俗称豆虫，危害大豆、刺槐等，可食用。
 
174.【尺蛾】 geometrid moths 鳞翅目尺蛾科（Geometridae）的通称，又称尺蠖，俗称步曲、造桥虫。体瘦狭，多暗色。翅大而薄，停息时平铺。飞翔力较弱。幼虫体细长，行动时常一屈一伸地前行。许多种类为农林害虫。
 
175.【尺蠖】 geometrid moths 尺蛾幼虫的俗称。
 
176.【桑尺蠖】 mulberry looper（Hemerophia atrilineata）鳞翅目尺蛾科。体长16毫米，灰褐色。前翅灰色，有2条暗黑色斜波状纹，外缘为不规则齿状。幼虫灰褐色，停息时直立叶背。桑树重要害虫。
 
177.【油茶尺蠖】（Biston marginata）鳞翅目尺蛾科。体粗短，灰褐色。前翅基部有两条平行黑褐色纹，中央有一条黑褐色横纹。幼虫黄色，杂有黑褐色斑点，头顶左右有二角状突起，食叶，危害油茶。
 
178.【桑蚕】 silkworm又称家蚕（Bombyx mori）鳞翅目蚕蛾科。翅展39～43毫米。体及翅灰白色，腹部背中央有成丛白色长毛。幼虫食桑叶。茧为重要的缫丝原料。驯化饲养历史悠久。
 
179.【桑蟥】 mulberry white caterpillar（Rondotia menciana）俗称白蚕、蟥虫。鳞翅目蚕蛾科。翅展35～40毫米。体及翅黄色，胸部和腹部背面有黄褐色长毛。前、后翅均有两条黑褐色波状纹。幼虫食桑叶，是桑树重要害虫。
 
180.【柞蚕】 perny silk moth（Antheraea pernyi）鳞翅目天蚕蛾科。体大型，长约40毫米，被有黄褐色鳞毛。四翅各有一白色眼斑及斜条纹。幼虫绿、黄或天蓝色等，体有毛瘤，刚毛挺直，主要取食栎和柞树叶。茧椭圆形，黄褐色，可作缫丝原料。
 
181.【蓖麻蚕】 eri-silk worm（Philosamia cynthia ricina）鳞翅目天蚕蛾科。翅展95～110毫米。体被褐白相间的鳞毛。翅棕褐色，各有一白色月形纹和横纹。幼虫白、黄或天蓝色，有黑斑或无斑，喜食蓖麻叶。茧呈榧子形，白色，可作绢纺原料。
 
182.【樟蚕】（Eriogyna pyretorum） 又称天蚕。鳞翅目天蚕蛾科。翅展约100毫米。体及翅灰褐色，胸部密披黑褐色茸毛，腹部各节间有白色茸毛环。幼虫蓝色，取食樟、枫、榆等树叶。产地居民常剖取熟蚕丝腺，用醋泡浸，拉长成线，用作外科缝线和钓鱼丝。
 
183.【弄蝶】 skippers 鳞翅目弄蝶科（Hesperiidae）的通称。体小至中型，外形似蛾，色暗，常有金属光泽。触角棍棒状，末端多呈钩状。一般白天活动，飞行迅速如跳跃。幼虫喜食禾草、棕榈和竹叶等。
 
184.【稻苞虫】 rice skipper（Parnara guttata），又称结虫、直纹稻苞虫。鳞翅目弄蝶科。体长17～19毫米，黑褐带金黄色。前翅有8个半透明的白斑，排成弧形；后翅有4个白斑，排成一列。幼虫能吐丝将稻叶卷折成苞。水稻重要害虫。
 
185.【凤蝶】 swallowtails鳞翅目凤蝶科（Papilionidae）的通称。大型蝴蝶。翅色彩绚丽，后翅外缘呈波状或有尾突。幼虫光滑无毛，前胸背面有一枚分叉的小囊，触动时即突然伸出，并发出臭气，常以柑橘类树叶为食。多分布热带。
 
186.【金带喙凤蝶】 kaiser-I-hind（Teinopalpus imperialis）鳞翅目凤蝶科。翅背面淡绿色。前翅有黄色和深绿色横带；后翅有亮黄斑，外缘锯齿状，雄蝶有１尾突，雌蝶有２尾突。珍稀蝶类，分布中国西南和南亚一带。
 
187.【金斑喙凤蝶】 golden kaiser-hind（Teinopalpus aureus）鳞翅目凤蝶科。前翅绿金黄色，有深绿色和浅灰色横带；后翅中部有一大金黄色斑，外缘锯齿状，雄蝶有１尾突，雌蝶有２尾突。极珍稀蝶类，仅残存中国华南一带。
 
188.【褐凤蝶】（Bhutanitis）鳞翅目凤蝶科褐凤蝶属（Bhutanitis）的通称。体被粗毛。体及翅黑色有黄色斑纹。后翅有红色及蓝色斑点。高山产珍稀蝶类，仅分布中国、不丹及印度。以三尾褐凤蝶和二尾褐凤蝶最为著名。
 
189.【裳凤蝶】（Troides helena）鳞翅目凤蝶科。体大型、美丽。前翅黑色，有白色条纹；后翅背面金黄色，沿外缘有相连的锐三角形黑斑，后缘黑色。仅分布中国华南和东南亚一带。
 
190.【金裳凤蝶】 （Troides aeacus）鳞翅目凤蝶科。体大型、美丽。前翅黑色，有白色条纹；后翅背面金黄色，沿外缘有相连的钝三角形黑斑，后缘黑色。分布中国南方和越南至印度一带。
 
191.【虎凤蝶】（Luehdorfia）鳞翅目凤蝶科虎凤蝶属（Luehdorfia）的通称。体中型强壮。翅底黑色，有黄色虎纹状横带，沿后翅外缘有红色、蓝色及黄色斑。胸部背面有长的软毛，绯红色。后翅有一个尾突。仅分布中国、俄罗斯、朝鲜和日本。
 
192.【中华虎凤蝶】 Chinese luehdorfia （Luehdorfia chinensis）鳞翅目凤蝶科。体长13～18毫米，黑色。翅上有黄色横纹，后翅外缘呈环形并列着数个红、蓝和黄等色圆形或新月形斑。幼虫取食细辛和杜衡。仅分布长江中下游一带。
 
193.【绢蝶】 parnassians鳞翅目绢蝶科（Parnassiidae）。体中型，白或黄色，被密毛。翅面鳞片较少，半透明，有黑色、红色或黄色的斑点或环状，外缘圆滑。主要分布欧亚大陆高山寒冷地带。
 
194.【阿波罗娟蝶】 Parnassius apollo鳞翅目绢蝶科。翅乳白色，雌性略发黄。前翅有多个深浅不一的黑斑，外缘半透明；后翅有数个黑斑和外圈黑中央白的红斑，后缘灰黑。分布亚洲北部和欧洲。
 
195.【粉蝶】 pierids鳞翅目粉蝶科（Pieridae）的通称。体中小型，白、黄、橙等色，有暗黑等斑纹。翅外缘圆滑。幼虫取食十字花科、豆科等植物。不少种类为农林业重要害虫。世界性分布。
 
196.【菜粉蝶】 cabbage white butterfly（Pieris rapae）又称白粉蝶、菜青虫。鳞翅目粉蝶科。翅白色，有灰黑斑。幼虫绿色，危害十字花科蔬菜。
 
197.【菜青虫】 cabbage white butterfly菜粉蝶幼虫的通称。
 
198.【蛱蝶】 brush-footed butterflies 鳞翅目蛱蝶科（Nymphalidae）的通称。体中至大型，翅色鲜艳。前足退化。翅外缘形状多不规则。幼虫头上常有突起，体节上有棘刺。不少种类为林木和作物害虫。
 
199.【枯叶蝶】（Kallima inachus chinensis） 鳞翅目蛱蝶科。以拟态著名。停息时两翅合拢，露出翅的反面，好象一片枯叶。幼虫取食靛蓝。产于中国长江流域。
 
200.【苎麻赤蛱蝶】 Indian painted lady（Vanessa indica）俗称卷叶虫。鳞翅目蛱蝶科。翅展67毫米。翅黑褐色，前翅外半部有白色小斑，中部有云形红色横纹；后翅暗褐色，外缘橘黄色，有4个黑斑排列其中。幼虫危害苎麻、黄麻、荨麻等。
 
201.【灰蝶】 blues 鳞翅目灰蝶科（Lycaenidae）的通称。中或小型蝶类，纤弱而美丽。触角有白环，眼周围白色。后翅外缘常有尾状突起及假眼斑。幼虫短而扁，贝状或蛞蝓状，喜食豆科植物。
 
202.【眼蝶】 satyrid butterflies 鳞翅目眼蝶科（Satyridae）的通称。多为中等蝶类，颜色暗而不鲜艳，翅上常有眼状或圆形斑纹，有警告作用。前足退化。幼虫多危害禾本科植物。世界分布。
 
203.【双翅目】 Diptera俗称蝇、虻、蚊。小至中型昆虫。体宽短或纤细。复眼大。口朝下，口器适宜刺吸和舔吸。中胸发达，前、后胸退化。前翅发达，膜质；后翅退化为平衡棒。幼虫蛆型，无足，水栖或陆栖。世界性分布。
 
204.【蝇】 flies蝇类的通称。双翅目芒角亚目（Aristocera）。体宽短。触角短，3节，具芒。幼虫无头和足，称为蛆。食性复杂。一些腐食性或吸血种类，能携带传播病原，是重要的卫生或畜牧害虫。一些种类是重要的农业害虫。
 
205.【虻】 flies双翅目短角亚目（Brachycera）的通称。包括虻科（Tabanidae）和食虫虻科（Asilidae）。触角短，一般3节，无芒。幼虫半头形，头壳背面略骨化。捕食性和腐食性种类较多。
 
206.【蚊】 mosquitoes双翅目蚊科（Culicidae）的通称。包括按蚊、库蚊和伊蚊。体纤细脆弱。触角有毛，雄蚊更显著。口器适宜刺吸。幼虫水生，俗称孑孓。雌蚊吸血，能传播疾病，是重要的卫生害虫。
 
207.【蠓】 biting midges 双翅目蠓科（Ceratopogonidae）的通称，俗称小咬。体微小，长1～3毫米。触角丝状。口器适宜刺吸。一些种类能追袭人畜，叮咬吸血，可传播疾病。
 
208.【小咬】 biting midges 即蠓。
 
209.【蚋】 black flies双翅目蚋科（Simuliidae）的通称，又称黑蝇。体型似蝇，长1～5毫米。头半球形，眼大而圆。触角短。口器适宜咬吸。雌成虫能猛烈咬刺和吸血，危害人畜，传播疾病。
 
210.【蛾蚋】 moth flies双翅目毛蠓科毛蠓亚科（Psychodinae）的通称。体型似蛾，暗灰色，体表有鳞毛。翅宽圆。为居室内厕所、厨房等潮湿地方的常见小型昆虫，不吸血，对人无害。
 
211.【大蚊】 crane flies双翅目大蚊科（Tipulidae）的通称。中至大型，似蚊，但体大而细长，足长而易断。头大，触角雌性线状，雄性梳状或锯齿状。成蚊不刺叮吸血，常见于水边或植物丛中。
 
212.【按蚊】 anopheles mosquitoes双翅目蚊科按蚊属（Anopheles）的通称。体多灰色，翅有黑白花斑，停立时身体一般与接触面成45°角。许多种类如中华按蚊、微小按蚊等是传播疟疾的重要媒介。
 
213.【库蚊】 culex mosquitoes 双翅目蚊科库蚊属（Culex）的通称。体多黄棕色，无花斑，停立时身体与接触面平行。有些种类如尖音库蚊、至乏库蚊等是流行性乙型脑炎等疾病的重要传播媒介。
 
214.【伊蚊】 aedes mosquitoes双翅目蚊科伊蚊属（Aedes）的通称。体黑色或棕色，多有白斑，停立时身体与接触面平行。有些种类如白纹伊蚊、仁川伊蚊等是流行性乙型脑炎等疾病的重要传播媒介。
 
215.【摇蚊】 midges双翅目摇蚊科（Chironomidae）的通称。体细弱微小，淡绿、黑或褐色。常于黄昏或日中集群飞舞，不叮人。幼虫水生，细长，体多为红色，俗称红（线）虫，在池塘和沟渠中常见，可作鱼饵。
 
216.【白蛉】 sand flies 双翅目毛蠓科（Psychodidae）的通称，又称蝶蝇、砂蝇。体型似蚊，但较小，多毛。停息时翅覆于背上。飞行姿势如跳跃。幼虫食腐烂的植物质、真菌和粪便等。成虫喜阴凉，有些种类吸血并可传病。
 
217.【牛虻】 horseflies双翅目虻科（Tabanidae）的通称，又称马蝇。体型似蝇，较大且粗壮，多毛。口器适宜刺吸。幼虫肉食性，捕食小动物。雌成虫有吸血习性，是人与牲畜多种疾病的传播媒介。
 
218.【马蝇】 horseflies即牛虻。
 
219.【食虫虻】 robber flies双翅目食虫虻科（Asilidae）的通称，又称盗虻。体中至大型，头胸大，腹部细长而略呈锥形。飞行迅速，擅捕食其他昆虫。幼虫生活在土中、朽木中或落叶下，亦为捕食性。
 
220.【胃蝇】 bot flies双翅目胃蝇科（Gastrophilidae）的通称。体粗，形似蜜蜂，被绒毛。口器退化，喙短。卵附着于马、驴、骡等寄主体毛上，后被寄主舔食入胃，幼虫寄生胃中。常见的有马胃蝇等。
 
221.【牛皮蝇】 northern cattle grub （Hypoderma bovis）双翅目皮蝇科。体型似蜜蜂，长15毫米，被细毛。幼虫寄生于牛、马皮下，老熟幼虫钻孔，危害寄主体质和皮革质量。
 
222.【食蚜蝇】 hover flies双翅目食蚜蝇科（Syrphidae）的通称。体小至中型，阔或细长，常有黑黄相间的横纹。体型似胡蜂或蜜蜂，但没有蛰刺或叮咬能力。善悬飞，有取食花蜜的习性。幼虫多捕食蚜虫、粉虱、叶蝉等,可应用于生物防治。
 
223.【实蝇】 fruit flies双翅目实蝇科（Tephritidae）的通称。体小至中型，黄或褐色。复眼大，常有绿色闪光。翅常有斑点或条纹，停立和爬行时常前后扇动。植食性。不少种类是水果和蔬菜的重要害虫，被列为重点检疫对象。
 
224.【柑橘大实蝇】 Chinese citrus fly（Bactrocera citri）俗称柑蛆。双翅目实蝇科。体长10～13毫米，淡黄褐色，胸背部有鲜黄色斑纹。翅透明，前缘和翅端有棕色斑。幼虫蛆形，食害果内组织，至腐烂或落果。柑橘害虫。
 
225.【地中海实蝇】 Mediterranean fruit fly（Ceratitis capitata）双翅目实蝇科。成虫体长4～4.5毫米。胸背部黑色，有灰黄色斑纹。是严重危害水果、蔬菜等的世界性重要检疫害虫。
 
226.【麦秆蝇】 European wheat stem maggot（Meromyza  saltatrix）俗称麦钻心虫、麦蛆。双翅目黄潜蝇科。体长3～4毫米，淡绿褐色或黄绿色，胸部背面有3条褐色纵纹。幼虫淡绿色，蛆形，从叶鞘侵入麦秆为害，形成白穗。小麦害虫。
 
227.【潜蝇】 leaf miners双翅目潜蝇科（Agromyzidae）的通称，又称潜叶蝇。体微小或小型，一般黑或黄色。幼虫蛆形，植食性，潜叶、茎或根，在叶上或根茎中形成各种形状的潜道。
 
228.【美洲斑潜蝇】 vegetable leaf miner （Liriomyza sativae）双翅目潜蝇科。体长1.3～2.3毫米，黑色，胸部背面有黄斑。幼虫蛆形，潜叶危害。是豆科、茄科和葫芦科蔬菜及菊科等农作物的重要害虫。
 
229.【果蝇】1 vinegar flies 双翅目果蝇科（Drosophilidae）的通称。体小型，长3～4毫米，暗黄色或黄褐色。复眼红色。触角第三节圆形，有羽状芒。成虫常见于烂果和腐败植物上，幼虫亦生活于其中。
 
2 vinegar fly特指黄果蝇（Drosophila melanogaster）。双翅目果蝇科。具有容易饲养、繁殖周期短、突变性状多、唾腺染色体大等特点，为重要的遗传学实验材料。
 
230.【狂蝇】 gad flies双翅目狂蝇科（Oestridae）的通称。体粗，生有密毛，形似蜜蜂。头大，颜阔，复眼小，有单眼。口器退化。幼虫胎生，寄生于牛、羊、鹿等的鼻腔，人亦有受害的。其中羊狂蝇为西北牧区常见种类。
 
231.【家蝇】 house fly（Musca domestica）双翅目蝇科。为室内外最常见蝇类。幼虫孽生于粪便和垃圾等污物中。能传染伤寒、霍乱、结核、痢疾等疾病。中国有舍蝇和欧洲家蝇。
 
232.【舍蝇】 oriental house fly（Musca domestica vicina），又称中国家蝇、东方家蝇。双翅目蝇科。家蝇舍蝇亚种。体长6～7毫米，灰褐色。分布全国各地，为室内常见蝇类，能传播多种疾病。
 
233.【舌蝇】 tsetse flies又称催睡蝇。双翅目舌蝇科（Glossinidae）。体中型，长5～10毫米，淡褐色。喙似针，端部有齿。生活于树木和灌丛地带，有吸食人及动物血液的习性，能传播致命性的疾病睡眠病。仅分布非洲热带及亚热带。
 
234.【丽蝇】 blow flies 双翅目丽蝇科（Calliphoridae）的通称。体中到大型，长5～7毫米，绿色或蓝色带金属光泽。幼虫腐食性，生活在动物尸体、腐肉及粪便中，寄生于动物的化脓伤口或肌肉内。可传播肠道传染病。
 
235.【麻蝇】 flesh flies双翅目麻蝇科（Sarcophagidae）的通称，又称肉蝇。体中至大型，银灰色，中胸背板有黑褐色纵纹。幼虫蛆形，多为肉食性，生活于腐败动植物质内，或寄生于昆虫和其他动物体内。
 
236.【寄蝇】 tachina flies双翅目寄蝇科（Tachinidae）的通称。体中至大型，多毛，暗灰色带褐色斑纹。腹部尤其腹末多鬃毛。幼虫多寄生于其他昆虫体内，可作为寄生性天敌应用于农、林、果、菜害虫的防治。
 
237.【膜翅目】 Hymenoptera俗称蜂、蚂蚁。小至中型昆虫。头大，复眼发达。口器适宜嚼吸。翅膜质，2对。腹部第一节常并入胸部，第二节常细缩成柄形。食性复杂，有植食性、捕食性和寄生性等。种类极丰富，世界性分布。
 
238.【叶蜂】 sawflies膜翅目广腰亚目叶蜂类的通称，又称锯蜂。体小至中型。前足胫节有2端距。雌虫产卵器锯状。幼虫躅形，除具3对胸足外，还有多对腹足，植食性，食叶、卷叶、潜叶、蛀果及作虫瘿等。
 
239.【锯蜂】 sawflies又称叶蜂。
 
240.【树蜂】 horntails膜翅目树蜂科（Siricidae）的通称。体中至大型，圆筒形，暗色或金属色。雌蜂有一粗长的产卵管，外包有鞘，能刺入树干产卵。幼虫营钻蛀生活，常引起真菌寄生，危害严重时常使树木枯死。为重要森林害虫类群。
 
241.【茎蜂】 stem sawflies膜翅目茎蜂科（Cephidae）。体细长。触角丝状。前胸较长，背板后缘平直。产卵管短，能收缩。幼虫蛀食草本或木本植物茎干。蛹形成于幼虫孔道内。常见的麦茎蜂常危害小麦等。
 
242.【尾蜂】 parasitic wood wasps膜翅目尾蜂科（Orussidae）的通称。体小圆筒形，暗色。头顶有瘤。卵一端有长管，产于树皮裂缝间或寄主体内。幼虫寄生天牛及吉丁虫等蛀害树木甲虫的幼虫。
 
243.【寄生蜂】 parasitic wasps寄生于鳞翅目、鞘翅目、双翅目等昆虫的幼虫、蛹及卵中的膜翅目蜂类，种类甚多，如姬蜂、小蜂、赤眼蜂等，在生物防治中多有应用。通过人工增殖后，再释放到环境中，对抑制害虫种群有明显作用。
 
244.【姬蜂】 ichneumon wasps 膜翅目姬蜂科（Ichneumonidae）的通称。体微小至大型，细弱。触角长丝状，多节。腹部细长或侧扁。产卵管最长可达体长的6倍。幼虫寄生于其他昆虫的体壁或体内。许多种类是农林害虫的重要天敌。
 
245.【茧峰】 braconid wasps膜翅目茧蜂科（Braconidae）的通称。体小至中型。翅细，脉序简单。有些种类雌蜂有等于或超过体长数倍的长形产卵管。幼虫寄生于其他昆虫的体壁或体内。许多种类是农林害虫的重要天敌。
 
246.【马尾峰】 Eurobracon yokohamae膜翅目茧蜂科。体长约19毫米，赤褐色。头部橙黄色，复眼褐色。触角丝状，长与体长相等。雌蜂产卵管很长，约150毫米。寄生于天牛及蛾类的幼虫。
 
247.【小蜂】 chalcid wasps 膜翅目小蜂科（Chalcididae）的通称。体微小，长0.2～5毫米。头横阔。触角短，膝状。胸部特别扩大，形成驼背。成虫食花蜜或动物伤口流出的液体。为其他昆虫幼虫及蛹的寄生虫，是害虫的重要天敌。
 
248.【金小蜂】 jewel wasps膜翅目金小蜂科（Pteromalidae）的通称。体微小，长1～2毫米，多呈鲜艳的金属颜色。复眼大，触角膝状。腹部短，没有明显的柄。产卵管短。寄生于各类昆虫，为防治害虫的重要天敌资源。
 
249.【黑青小蜂】 Dibrachys cavus又称红铃虫金小蜂。膜翅目金小蜂科。雌蜂体长约1.7～3.2毫米，黑色，翅有金属光泽。雄蜂体长约2毫米，腹部第一、二节间有半透明的黄白色带。为越冬棉红铃虫的重要外寄生性天敌。
 
250.【瘿蜂】 gall wasps 膜翅目瘿蜂科（Cynipidae）的通称，又称没食子蜂。体微小至小型，长1～6毫米，平滑有光或生绒毛。头小，触角刚毛状。成虫于秋季出现，在植物的芽、叶、茎或根的组织中产卵，形成虫瘿。
 
251.【卵蜂】 egg parasites寄生于各种昆虫卵内的寄生蜂，主要包括赤眼蜂科、柄翅卵蜂科及缘腹卵蜂科等。体细小。雌蜂以尾部的产卵管刺入害虫卵中产卵。在害虫卵内完成从卵到成虫的发育过程，直至成虫破壳而出。对害虫生物防治有重要意义。
 
252.【赤眼蜂】 minute egg parasites 膜翅目赤眼蜂科（Trichogrammatidae） 的通称。体极小，不足1毫米，黑色、暗褐色或黄色。触角膝状。复眼赤红色。前翅很阔，或狭而有缘毛。寄生于各类昆虫的体内。在生物防治中常有应用。
 
253.【翳螉】 Ammophila vagabunda 又称类我蜂。膜翅目泥蜂科。体长14～22毫米，黑色。雌虫腹部末端有蜇刺。独栖性，常以泥土在房屋墙壁、岩石、树木等处作巢，将猎捕的鳞翅目幼虫及蜘蛛等封贮，供子代幼虫食用。
 
254.【泥蜂】 mud-dauber wasps膜翅目泥蜂科（Sphecidae）的通称。体细长，腹部基端细杆状。黑色，有蓝、紫、绿等光泽，着黄、红等斑纹。常在建筑物、岩石、树木等处筑土室，猎捕鳞翅目幼虫及蜘蛛等，产卵后封贮于其中，供子代幼虫食用。
 
255.【土蜂】 scoliid wasps膜翅目土蜂科（Scoliidae）的通称。体小至大型，多毛，黑色，有白、黄、橙、红等斑纹。头部圆球形，触角短而弯曲。幼虫多寄生于金龟子幼虫。成虫常见于植物的花上。
 
256.【胡蜂】 hornets膜翅目胡蜂科（Vespidae）的通称，俗称黄蜂、马蜂。体中至大型，长9～40毫米，黄红等色，有黑褐等斑纹。群栖性，常在高大树上或房檐下筑巢，蜂群中有明显的分工现象，存在蜂后、工蜂和雄蜂三个级别。
 
257.【黄蜂】 yellow-jackets即胡蜂。
 
258.【马蜂】 paper wasps即胡蜂。
 
259.【蜾蠃】 potter wasps膜翅目蜾蠃科（Eumenidae）的通称，又称蜾蠃蜂。体中至大型，暗色，有白、黄、橙、红等斑纹。停息时翅纵行摺叠，多有褐色或紫色反光。常以泥土筑壶形巢，将猎捕的鳞翅目幼虫或蜘蛛贮藏其中，供子代食用。
 
260.【蚂蚁】 ants膜翅目蚁科（Formicidae）的通称。体小，多呈红褐或黑色。触角膝状。腹部与胸部连接处有1～2节呈结状突起。翅有或无。食性复杂。为筑巢群居的社会性昆虫，有明显的多型现象，包括雌蚁、雄蚁、兵蚁与工蚁等。
 
261.【切叶蜂】 leaf-cutting bees膜翅目切叶蜂科（Megachilidae）。体中至大型，形似蜜蜂，但较强壮而色深，被白、黄、褐红色毛。头和胸部等宽。雌性腹面有颜色鲜明的花粉刷。常切叶营巢。是豆科等植物的重要传粉媒介。
 
262.【地蜂】 burrowing bees膜翅目地蜂科（Andrenidae）的通称。体长5～18毫米。头、胸及足部丛生长毛。后足具长毛形成的花粉采集器。单独或群居生活。雌蜂在地下筑巢，采集贮藏花粉花蜜供幼虫生长，群居时小巢多达数千个。
 
263.【木蜂】 carpenter bees膜翅目木蜂族（Xylocopinae）的通称。体中至大型，粗壮，黑色有暗青绿光泽，少数被黄、白、红色密毛。翅色暗，常有虹彩。在干燥的木材上蛀孔营巢，对木结构建筑物危害较大。
 
264.【熊蜂】 bumble bees膜翅目熊蜂族（Bombinae）。体中至大型，长9～30毫米，粗壮，被黑、黄或橙色密毛。为筑巢群居的社会性昆虫，有蜂后、工蜂和雄蜂3个级别。成蜂采集和取食花粉花蜜过程中，对植物有传粉作用。
 
265.【蜜蜂】 honeybees膜翅目蜜蜂科（Apinae）的通称。体长8～20毫米，黄褐色至黑褐色。后足有花粉筐和花粉刷等特化构造。为营巢群居的社会性昆虫，有蜂王、雄蜂与工蜂等型。一些种类长期以来被人类驯养，以供采蜜和获得其他蜂产品。
 
266.【中华蜜蜂】 Chinese honeybee（Apis cerana）常简称中蜂。膜翅目蜜蜂科。体长10～16毫米，黄褐色，被浅黄色毛。腹部第三、四节红黄色，各节均有黑色环带。为南方主要家养蜜蜂品种。
 
267.【意大利蜜蜂】 Italian honeybee（Apis mellifera）常简称意蜂。膜翅目蜜蜂科。体长14～17毫米，形似中华蜜蜂，但略强壮。原产欧洲，现为世界各国主要家养蜜蜂品种。
 
268.【蚤目】 fleas通称跳蚤。小型寄生性昆虫。体侧扁，体表有鬃、刺或栉。头小，口器适宜刺吸。无翅。足发达，能爬善跳。腹部大。成虫以吸食兽类和鸟类血液为生，部分种类是鼠疫等疾病的传播媒介。世界性分布。
 
269.【跳蚤】 fleas 蚤目的通称。
 
270.【蜱螨亚纲】  节肢动物门蛛形纲。头、胸、腹愈合，体分颚体和躯体2部分，颚体有口器，躯体不分节。幼螨3对足，若螨和成螨4对足。包括蜱和螨，是蛛形纲中种类和数量极多、形态各异的类群，约50万种，已记述数万种。分布遍及陆地的各种生态环境，也有生活于海洋的类群。
 
271.【蜱】ticks  俗称狗豆子、草爬子。蜱螨亚纲蜱总科(Ixodoidea)。体长数毫米，饱食血液后可达1厘米。表皮革质，口器具倒齿，可刺入和固着于人、畜的皮肤内，吸食血液，传播多种病原体，引起森林脑炎、莱姆等疾病。
 
272.【螨】mites  蜱螨亚纲的类群。多数体长不及2毫米。外部形态、栖息场所多样，与人类关系密切，危害农作物、果树或寄生于人、畜，传播疾病，也有自由生活或捕食害虫的种类，是天敌资源。
 
273.【甲螨】 beetle mites  蜱螨亚纲甲螨目(Oribatida)。体壁坚硬，褐色，似甲虫。体长0.2~1.5毫米。已知种类达万种。多见于枯枝落叶、土壤表层。取食菌类、腐烂植物，对有机物质的分解，增强土壤肥力有重要作用。
 
274.【植绥螨】  蜱螨亚纲植绥螨科(Phytoseiidae)。橘红或黄色，体长0.4~0.5毫米。体有背板。常见于植物，行动迅速，善捕食小型昆虫或螨类，是有利用价值的害虫天敌。
 
275.【瘿螨】gale mites  蜱螨亚纲瘿螨总科(Eriophyoidea)。体长0.2毫米，蛆状，足2对，口器针状。危害植物，致叶片锈色，或引起组织增生，形成袋状、毛毡状的螨瘿。也有为害叶芽，致叶片扭曲变形。瘿螨可传播植物病毒，引起植物病害。
 
276.【疥螨】  蜱螨亚纲疥螨科(Sarcoptidae)。体长不及1毫米，半球形，乳白色，口器蹄铁状。可在人、禽类和哺乳动物表皮内穿凿隧道，寄生部位毛发脱落，引起丘疹、水疱、奇痒不止，俗称疥癣病。
 
277.【粉螨】 flour mites  蜱螨亚纲粉螨总科(Acaroidea)。体长不及1毫米，乳白色，背面有长毛。仓储螨类，危害谷类、畜产品、中药材等，也有的种类在土壤、鸟窝或动物巢穴内，取食有机物的碎屑。
 
278.【恙螨】 chigger mites  蜱螨亚纲恙螨科(Trombiculidae)。幼螨足3对，葫芦形，寄生于人、鼠等动物体外，吸食体液，传播立克次体，引起恙虫病。幼螨落入土壤内蜕变为4对足的若螨和成螨。成螨橘红色，体被密毛，自由生活。
 
279.【根螨】 root mites  蜱螨亚纲粉螨科(Acaridae)根螨属(Rhizoglyphus)。体小，白色，危害大蒜、洋葱、马铃薯和观赏植物的鳞茎、块根。受害植物的根、茎部分腐烂变质，影响产量和贮藏。
 
280.【革螨】 gamasid mites  蜱螨亚纲中气门目(Mesostigmata)。气门位于中部体侧，体表革质，背、腹面有数目不等的骨板。种类繁多，生活方式多样。寄生于人和动物，引起流行性出血热等疾病。有的种类可捕食螨类、昆虫，或附着于昆虫体外，被动携播。
 
281.【尘螨】 dust mites  蜱螨亚纲麦食螨科(Pyroglyphidae)。体长0.5毫米以下，乳黄色，体表具密纹。室内尘埃、地毯、被褥、面粉等为孳生场所，取食有机物碎屑。粉尘螨、屋尘螨为常见种类，是尘螨性哮喘、过敏性鼻炎等疾病的过敏源。
 
282.【跗线螨】  蜱螨亚纲跗线螨科(Tarsonemidae)。体长0.2毫米，口器针状，雌螨第四对足细，末端有长毛，雄螨第四对足粗大，末端有爪。取食植物、菌类或藻类，有些种类发现于贮藏品、中药材或寄生于昆虫。侧多食跗线螨(茶黄螨)是茶叶、蔬菜等经济作物常见的害螨。
 
283.【蠕形螨】 demodicid mites  (Demodicidae)，又称毛囊螨。蜱螨亚纲蠕形螨科。体长0.2毫米，白色，蠕虫状，具细横纹。寄生于人或犬、牛等动物毛囊内，取食皮下分泌物，引起皮炎，动物患部蜕毛，产生脓包或鳞屑，致皮革业受损。
 
284.【水螨】 water mites  蜱螨亚纲水螨群(Hydrachnellae)。体长0.5～1 毫米，红、绿等色，须肢适于抱握，足有细长游泳毛。见于溪流、湖泊，温泉等各类水域。幼螨寄生于昆虫，若螨和成螨扑食水生昆虫、螨类、甲壳类。种类极多，世界分布。
 
285.【蜂螨】 bee mites  重要种类有大蜂螨(Varroa jacobsoni)和小蜂螨(Tropilaelaps clareae)。大蜂螨长约1.2 毫米, 褐色, 扁圆形。小蜂螨长1 毫米，棕黄色，椭圆形。蜂螨可潜入蜜蜂幼虫的蜂房内产卵繁殖，完成发育。吸食蜜蜂及幼虫体液，致蜜蜂不能羽化，寿命缩短，蜂群衰弱，甚至死亡，给养蜂业带来严重损失。
 
286.【叶螨】 spider mites  又称红蜘蛛。蜱螨亚纲叶螨科(Tetranychidae)。长0.5~1毫米。红、黄或绿色，表皮柔软，口器针状。棉花、果树、林木和观赏植物的重要害螨。
 
287.【红蜘蛛】 red spider mites 即叶螨。
 
288.【截形叶螨】 Tetranychus truncatus   蜱螨亚纲叶螨科。体长0.5毫米，深红色，体侧有黑斑。危害棉花、玉米、豆类、蔬菜等经济作物。分布中国各地。
 
289.【朱砂叶螨】 carmine spider mite  蜱螨亚纲叶螨科。体长0.5毫米，锈红色。寄主植物广泛，是棉花的重要害螨，常致叶片脱落，造成棉花严重减产。分布中国各地。
 
290.【二斑叶螨】 two spotted spider mite蜱螨亚纲叶螨科。体长0.5毫米，绿色，体侧有三裂形黑斑。寄主植物广泛，危害苹果等果树。主要分布中国北方果树产区。
 
291.【苹果全爪螨】 European red mite蜱螨亚纲叶螨科。深红色，背毛粗壮。苹果、梨等蔷薇科果树常见的害螨，受害叶片呈黄色斑点，严重时可致落叶，减产。分布中国北方。
 
292.【柑橘全爪螨】 citrus red mite 蜱螨亚纲叶螨科。红色，背毛长，生于粗大的毛瘤上。柑橘常见的害螨，受害的柑橘叶片失绿，脱落，造成减产。分布中国南方。
 
293.【山楂叶螨】 hawthorn spider mite  蜱螨亚纲叶螨科。深红色，背毛13对。苹果、梨、桃等果树常见的害螨，主要分布中国北方。
 
 

参考文献
 
1.       《中国大百科全书》生物卷Ⅰ-Ⅲ。中国的大百科全书出版社。1991。
2.       《中国农业百科全书》昆虫卷。农业出版社，1990。
3.       《中国农业昆虫学辞典》（上、下册）。中国科学院动物研究所主编。农业出版社。1986。
4.       《简明不列颠百科全书》1～16卷。中国的大百科全书出版社。1982～91。
5.       《辞海》百科增补本。上海辞书出版社。1982。
6.       《辞海》修订本，生物分册。上海辞书出版社。1978。
7.       【英】O.W理查兹 & R.G戴维斯著《依姆斯昆虫学纲要》。科学出版社，1982。
8.       王音等，《观赏昆虫大全》。中国农业出版社。1994。
9.       刘友樵，白九维，《中国经济昆虫志》第十一册（鳞翅目：卷蛾科（一）。科学出版社。1977。
10.    吴燕如，周勤，《中国经济昆虫志》第五十二册（膜翅目：泥蜂科）。科学出版社。1996。
11.    张维球等，《农业昆虫学》。农业出版社。1981。
12.    忻介六等，《昆虫形态分类学》。复旦大学出版社。1985。
13.    李铁生，《中国经济昆虫志》第十三册（膜翅目：胡蜂总科）。科学出版社。1985。
14.    杨冠煌，《中国昆虫资源利用和产业化》。中国农业出版社。1998。
15.    周尧，《中国蝴蝶分类与鉴定》。河南科学技术出版社。1998。
16.    周尧等，《中国经济昆虫志》。第三十六册（同翅目：蜡蝉总科）。科学出版社。1985。
17.    范滋德主编，《中国常见蝇类检索表》第二版，科学出版社。1992。
18.    南开大学等五校合编，《昆虫学》。高等教育出版社。1980。
19.    胡萃等，《茶尺蠖》。上海科学技术出版社。1994。
20.    袁锋，《昆虫分类学》。中国农业出版社。1993。
21.    章士美等，《中国农林昆虫地理分布》。中国农业出版社。1996。
22.    萧刚柔，《拉英汉蜘蛛、昆虫、线虫、蜱螨名称》。中国林业出版社。1997。
23.    黄大卫，《中国经济昆虫志》第四十一分册（膜翅目：金小蜂科（一）。科学出版社。1993。
24.    管致和，《昆虫学通论》（第二版）。农业出版社。1993。
25.    蔡邦华，《昆虫分类学》（上，中，下册）。科学出版社。1956，1973，1985。
（袁德成）
** [2011-12-18 Sun 15:26] 印象海伦
印象海伦
2008年02月11日 22:06     来源：     作者：【亚拉巴马州】庄金陵 【放大 默认 缩小】
　　第一次认识海伦是10多年以前，那时我刚到美国不到半年，还没有上学，在附近的一家中餐外卖店做经理。其实就是打工，每天收银、订货、接电话，什么都干。厨房里有一个扎着马尾辫、左耳戴个大金耳环、会讲中国话的大厨，还有一个老墨帮着打杂。整个店一共就我们3个人，一天工作十几小时，忙得够呛，晚上回去还要结账。每天昏天黑地，来美国几个月了，我也不知道外面的世界是否真的精彩。

　　一天下午，朋友彼得来看我，同来的还有海伦，原来他们在同一餐馆打工做服务生。海伦穿着一件丝质的中式棉袄，浅粉色的底，上面缀满了朵朵碎花，看上去很鲜艳。那件中式棉袄裁剪得很得体，使得海伦窈窕的身段看上去韵味十足。

　　那天海伦两只手四指并拢地插在棉衣口袋里，只露出两个拇指在口袋外面，不做作，却很优雅。她的一举一动透着上海人的灵秀劲，会说话的眸子，一顰一笑都是故事。

　　我们第一次见面，海伦话不多，微笑着静静地在边上听彼得和我聊天。只是到了最后，海伦问我：“怎么样，喜欢美国吗？”我略有忿忿：“不怎么样，一天到晚打工呐。”她笑笑，很平静地回答：“打工不是很好嘛，许多人不都是从打工这样过来的。”她的声音不大，语气中却透着坚毅和泼辣，很像《北京人在纽约》里的阿春，也有人说更像《沙家浜》里的阿庆嫂。这就是第一次见到海伦的印象。

　　那时，海伦的先生在一所大学做博士后，儿子上小学，女儿才1岁。他们全家来美国不久，家里还不富裕，她就把女儿托给妈妈，自己出来打工。

　　海伦手脚麻利，做事利索，中餐馆里里外外的那点事对她而言不是问题，于是很快她便受到大家的好评。海伦的英语是到了美国才开始学的，现在讲得比他做教授的先生还流利。跟她的普通话一样，海伦的英语带着浓浓的上海口音，听起来另有一番滋味，老美句句听得懂，出去买东西，上馆子，都是她开口。

　　海伦是个有追求、做事果断好强的人。那时，她在餐馆打了几年工，天天做企台，英语突飞猛进，不久她便自己开餐馆做了老板，真的成了阿春。做了几年老板，赚了些钱，她又突然把店卖了，理由很简单——这个世界性别歧视太严重，明明我是老板，我的先生什么都不管，可他偶然来一次店，大家还总是一个劲地称他老板，叫我老板娘，是否太不公平了？！

　　卖了店，海伦就去学校读书了，说要多学点知识。她学的是护士专业，之所以选择这个专业，理由也很简单，一则，美国紧缺护士；二则，她说她有一颗爱心。

　　原先在上海念书时，海伦学的是有机化学专业，现在转学护士，一切都要从头开始，所有的知识对她说都是新东西，难度可想而知了。天份加上勤奋，使得海伦两年后顺利地把护士文凭拿了，接着又把护士的执照考到手。

　　那时她每天清晨四点钟起床，去麦当劳买杯咖啡，就在那背单词，一直到六点钟，然后去上课，几乎天天如此，整整坚持了两年。

　　毕业后，她先在一家大医院做了半年，积累了经验，后又转到政府机构负责性病工作的检测和防治，一直做到现在，现在她成了性病防治专家。每每听海伦自己道来，感觉总是很自豪的。记得知名作家任颜芳拜访了海伦一家后，写过一篇《一个中国女人的美国梦》，文章里的女主角就是海伦。

　　我和海伦一家熟了，去他们家做客，她什么都讲。第一次和先生恋爱、第一次生小孩、第一次打工、第一次做餐馆老板、第一次听歌、第一次看海、第一次开车、第一次讲英语、第一次走进课堂读书、第一次在政府机构工作……林林总总，许许多多的第一次，留下许许多多难忘的回忆。

　　前不久海伦刚从上海度假回来，好客的海伦热情邀请大家去她家玩。充满节日气氛的客厅里洋溢着温馨，海伦坐在沙发上，身子靠着先生，兴高采烈地讲述着她在上海与初恋情人见面的故事，惟妙惟肖。

　　海伦的先生坐在她旁边，只是笑，不说话。满脸灿烂的海伦娇情地说，她先生最大的成就就是娶了她做太太。于是，客人们一起跟着开怀，笑声带着祝福，弥漫了整个客厅。我想，这就是佛学里缘的最好诠释，有缘无缘，缘起缘落，古今多少美丽故事不都是一个缘字演义而来的吗？

　　轻轻地挥挥手告别了昨天，不经意间10多年过去了。现如今海伦的先生已成了教授，每年有充裕的科研经费，时不时在大洋两边做些文化交流。儿子大学毕业在杜邦公司做工程师，女儿读高中，长得亭亭玉立，各方面都出类拔萃。海伦自己在政府机构工作，幸福的一家子让人怎一个羡慕了得。

　　问及海伦还有什么愿望？海伦说，最大的愿望是退休后回中国去做一名普及防治性病工作的志愿者，把自己在这里学的知识贡献给养育过她的祖国。

　　她说，每当看到她的病人在美国受到全社会关心，生活过得比没患病的人还好，就觉得中国在这方面还有很多缺憾。她真情的叙述、来自肺腑的表白，动情处的泪眼婆娑，让人无不为之感动。

　　生活伴着希望，希望让生活变得美好。祝愿海伦早日实现她的愿望，做一个播撒爱心的使者，圆自己的一份心愿。
** [2012-01-16 Mon 22:01] termites
1/16  1 and 4 无活虫
** [2012-01-17 Tue 08:21] pronura is called telson tail. (sometimes)
** [2012-01-17 Tue 08:26] epiproct and paraprocts
** [2012-02-23 Thu 11:11] The many costs of sex

too many new words.
** [2012-02-27 Mon 09:03] Parental care Sex conflict
*** Fig.1
An extensive literature search revealed 124 experiments
that investigated the effect of mate removal or manipulation
to reduce parental care in animals.
** [2012-03-20 Tue 15:34] Instar determination using Gaussian mixture model
 
Growth of insect nymph is continuous, while the growth of the exoskeleton is not. Heavily sclerotized structures, such as headcapsules, remain approximately the same size during a stadium. The most measurable changes in size occur following molts. These special characters can be used to differentiate instars.
 
Actually the morphological measurements can be viewed as a normal distribution in each instar. Thus, samples from a given population of insects are a mixture of several normal distributions, one for each instar. This assumption is reasonable because measurements from individuals from the same ontogenetic stage are often distributed normally (Sokal & Rohlf 2011). As a result, the instars determination problem can be addressed using Gaussian mixture model.
 
In my program, several characters (head width, pronotum width and length, weight) will be used individually (univariable) or combined (multivariables) in the GMM to get the distribution of each instar.
 
There are R packages (mixtools, HDclassif) available in CRAN, so I do not implement to algorithms myself.
