** [2011-05-22 周日 23:07] 毕业赠言

又到了一个离别的季节，每个人都会有一个新的开始。我大约是那种总不死心，认为我能改变自己和别人的人。
不管现在如何，我总觉得有些东西，和大家分享比较好。

*** 做事 120 449 912 418

我们处于一个社会之中，为社会和他人做事，即是为自己做事，才会有生存的空间。有时候，我们会感慨现在的社会太功利，甚至，有时候
会受到种种不情愿的对待。与其抱怨，还不如，做些事情。作为社会的一份子，当一个个体什么都做不了的时候，或者，什么都不愿意做的时候，
这个个体已经没了存在的必要了。不爽的时候，做事来改变；做事，才会改变。

*** 爱人

当物是人非，说什么，如果上天再给我一次机会，已经没有意义了。

以诚待人，总不会有什么过错。

*** 惜物

不知道，我们所处的社会出了什么问题，每一个个体都不错。但是大家在一起，就会做出一些让人哭笑不得的事情。也许很讽刺，我们公有制国家，个体
却是最不爱惜公物的。每一个人，都从一己出发，想问题；哪里会有，我们共同的答案。真有些担心，我们所处的社会是无解的。

*** 学习

聪明的人，从别人的错误中学习；一般人，从自己的错误中学习；傻子，自己犯错误让别人来学习。

学习别人的方法有很多，最简单的莫过于看书。不管有多少人批判“书中自有千钟粟，书中自有黄金屋，书中自有颜如玉”；看点应该看的书，总没有什么坏处。


** 我们班主任的临别赠言

同学们：
    我怀着无比难舍的心情给大家写下这。四年的努力，大家都顺利的毕业了， 真心祝贺你们，在你们人生的道路上，这又是一个可喜的成绩！一个了不起的成绩！
    明天，我们的自云和良平就要去工作岗位，陆陆续续的，奇高，李攀，樊荣，嘉斌，本龙，卢飞，苏通，鹏艳，候斐，段骁，应潇，小强，还有礼明都会向着自己人生的目标和奋斗目标走去，同学们，如果说工作是人生的一种锤炼，那学习又何偿不是？我们的克雪，银君，乾隆，梦荷，小果，佳佳，二虎，黄勇，张凯、明霞、翠平，永琴，还有最远的武浩，大家都要在一个时空平台上去努力见证人生的成长，所以，我想说无论是工作，还是继续学习，我们都要付出我们百分一百的努力，只有真真正正的努力过，活着才不会后悔！
人一生的路有许许多的变化，或许在工作中会有不如意，或许在学习中会有这样或那样的困难，我们该怎么办？气馁、报怨？不，不是那样的，我们绝对不可以怨天尤人，反而要把这种精力放到寻求解决问题的思路上来，如果你尽力了，事情还是没有圆满，你权且将它看作是一种缘份吧，佛家如是说，一切皆缘，尽力了只能说明你和事情的缘份恰巧到那一步而已。四年前能够作为你们的班主任，这是我和你们的缘份，也是我这一生中最大的荣幸，因为大家都那么优秀，那么出色，28个人就有28个优点，而这些优点折射开来就是28条人生的轨迹，周老师心里永远为你们感到骄傲！写下28这个数字的时候，非常的想念段骁了，水痘的特殊原因他没能参加今天的毕业宴会，心里总觉得28人的家庭突然有了一点点的缺憾，在这里希望他早点好起来，顺顺利利的答辩，完成他本科阶段的最后一个任务！
    4年的缘份不会随着你们毕业而减少，之后不是你们的班主任了，可是无论何时，周老师永远都是你们的朋友，这里永远是你们的家，随时都欢迎你们的归来！
    踏入社会了，或许你们会发现社会的本质是那样的现实，复杂甚至于难于理解，苦其心志，劳其体肤，一定要学会忍耐和包容，对别人包容，也对自己包容，那样我们才会开心，没有什么比追逐开心的生活更重要！记住，忍耐！包容！
    多年以后，希望在这个28人的大家庭里，仍能与你们一起分享快乐，分享你们的成功！
    最后，祝我的同学们前程锦绣，幸福键康！
    永远爱你们！

                                                                          周刚
                                                             2011/ 5/23
