=pod

=head1 Name

Instropection of an object

=head1 Methods

The methods included

=head2 WHAT

    1.WHAT # Int()

=head2 ^methods

    1.^methods(:local).join(',')

    Int,Num,Rat,FatRat,abs,Bridge,chr,sqrt,base,expmod,is-prime,floor,round,ceiling,sign,conj,rand,sin,asin,cos,acos,tan,atan,atan2,sec,asec,cosec,acosec,cotan,acotan,sinh,asinh,cosh,acosh,tanh,atanh,sech,asech,cosech,acosech,cotanh,acotanh,unpolar,cis,Complex,log,exp,truncate,isNaN,Real,log10,roots,succ,pred,WHICH,perl,Bool,Str,Numeric,ACCEPTS,gist

=head2 ^attributes

the attributes of a object

=head2 ^parents

the parents of a object class

=head2 ^mro

inherentance path

=cut
